import { Question } from '@/components/grammar/GrammarTestRunner';

export const tests: Record<string, Question[]> = {
  "test-1": [
    { "question": "___ is calling you?", "options": ["Who", "Whom", "Whose", "Which"], "answer": "Who", "explanation": "કર્તા (Subject) જાણવા માટે 'Who' વપરાય છે. (કોણ તમને બોલાવે છે?)" },
    { "question": "___ did you meet yesterday?", "options": ["Whom", "Who", "Whose", "What"], "answer": "Whom", "explanation": "કર્મ (Object) જાણવા માટે 'Whom' વપરાય છે. (તમે ગઈકાલે કોને મળ્યા?)" },
    { "question": "___ car is this?", "options": ["Whose", "Who", "Whom", "Which"], "answer": "Whose", "explanation": "માલિકી (Possession) જાણવા માટે 'Whose' વપરાય છે. (આ કોની કાર છે?)" },
    { "question": "___ is your favorite color?", "options": ["Which", "What", "Who", "Whose"], "answer": "Which", "explanation": "પસંદગી માટે 'Which' વપરાય છે. (તમારો મનપસંદ રંગ કયો છે?)" },
    { "question": "___ is your father?", "options": ["What", "Who", "Which", "Whom"], "answer": "What", "explanation": "વ્યવસાય જાણવા માટે 'What' વપરાય છે. (તમારા પિતાજી શું કરે છે?)" },
    { "question": "___ do you live?", "options": ["Where", "When", "Why", "How"], "answer": "Where", "explanation": "સ્થળ (Place) જાણવા માટે 'Where' વપરાય છે. (તમે ક્યાં રહો છો?)" },
    { "question": "___ will you come?", "options": ["When", "Where", "Why", "How"], "answer": "When", "explanation": "સમય (Time) જાણવા માટે 'When' વપરાય છે. (તમે ક્યારે આવશો?)" },
    { "question": "___ are you late?", "options": ["Why", "When", "Where", "How"], "answer": "Why", "explanation": "કારણ (Reason) જાણવા માટે 'Why' વપરાય છે. (તમે મોડા કેમ છો?)" },
    { "question": "___ do you go to school?", "options": ["How", "Why", "When", "Where"], "answer": "How", "explanation": "રીત (Manner) જાણવા માટે 'How' વપરાય છે. (તમે સ્કૂલ કેવી રીતે જાઓ છો?)" },
    { "question": "___ water do you need?", "options": ["How much", "How many", "How far", "How long"], "answer": "How much", "explanation": "Uncountable જથ્થા માટે 'How much' વપરાય છે. (તમારે કેટલું પાણી જોઈએ?)" }
  ],
  "test-2": [
    { "question": "___ students are there?", "options": ["How many", "How much", "How far", "How long"], "answer": "How many", "explanation": "Countable સંખ્યા માટે 'How many' વપરાય છે. (ત્યાં કેટલા વિદ્યાર્થીઓ છે?)" },
    { "question": "___ is the station from here?", "options": ["How far", "How long", "How much", "How many"], "answer": "How far", "explanation": "અંતર (Distance) જાણવા માટે 'How far' વપરાય છે. (સ્ટેશન કેટલું દૂર છે?)" },
    { "question": "___ will you stay here?", "options": ["How long", "How far", "How much", "How often"], "answer": "How long", "explanation": "સમયગાળો (Duration) જાણવા માટે 'How long' વપરાય છે. (તમે કેટલા સમય રહેશો?)" },
    { "question": "___ do you exercise?", "options": ["How often", "How long", "How much", "How far"], "answer": "How often", "explanation": "Frequency જાણવા માટે 'How often' વપરાય છે. (તમે કેટલી વાર કસરત કરો છો?)" },
    { "question": "The man ___ is standing there is my uncle.", "options": ["who", "whom", "whose", "which"], "answer": "who", "explanation": "વ્યક્તિ માટે કર્તા સ્થાને 'who' વપરાય છે. (જે માણસ ત્યાં ઊભો છે તે મારો કાકા છે.)" },
    { "question": "The boy ___ you helped is clever.", "options": ["whom", "who", "whose", "which"], "answer": "whom", "explanation": "વ્યક્તિ માટે કર્મ સ્થાને 'whom' વપરાય છે. (જે છોકરાને તમે મદદ કરી તે હોશિયાર છે.)" },
    { "question": "The girl ___ bag was lost is crying.", "options": ["whose", "who", "whom", "which"], "answer": "whose", "explanation": "માલિકી દર્શાવવા 'whose' વપરાય છે. (જે છોકરીની બેગ ખોવાઈ તે રડી રહી છે.)" },
    { "question": "The dog ___ bit me was mad.", "options": ["which", "who", "whom", "whose"], "answer": "which", "explanation": "પ્રાણી/વસ્તુ માટે 'which' વપરાય છે. (જે કૂતરાએ મને કરડ્યો તે ગાંડો હતો.)" },
    { "question": "This is the best book ___ I have ever read.", "options": ["that", "which", "who", "whom"], "answer": "that", "explanation": "Superlative પછી 'that' વપરાય છે. (આ સૌથી સારું પુસ્તક છે જે મેં વાંચ્યું છે.)" },
    { "question": "By ___ was this book written?", "options": ["whom", "who", "whose", "which"], "answer": "whom", "explanation": "Preposition (By) પછી 'whom' વપરાય છે. (આ પુસ્તક કોના દ્વારા લખાયું?)" }
  ],
  "test-3": [
    { "question": "The house in ___ I live is old.", "options": ["which", "who", "whom", "that"], "answer": "which", "explanation": "Preposition (in) પછી 'which' વપરાય છે. (જે ઘરમાં હું રહું છું તે જૂનું છે.)" },
    { "question": "___ students passed the exam.", "options": ["Many", "Much", "A little", "Little"], "answer": "Many", "explanation": "Countable (students) માટે 'Many' વપરાય છે. (ઘણા વિદ્યાર્થીઓ પાસ થયા.)" },
    { "question": "I have ___ friends here.", "options": ["a few", "few", "a little", "little"], "answer": "a few", "explanation": "થોડા પણ છે (Positive meaning) માટે 'a few' વપરાય છે. (મારે અહીં થોડા મિત્રો છે.)" },
    { "question": "___ people came to the meeting.", "options": ["Few", "A few", "Little", "A little"], "answer": "Few", "explanation": "ભાગ્યે જ કોઈ (Negative meaning) માટે 'Few' વપરાય છે. (ભાગ્યે જ કોઈ મીટિંગમાં આવ્યું.)" },
    { "question": "I don't have ___ time.", "options": ["much", "many", "few", "a few"], "answer": "much", "explanation": "Uncountable (time) માટે 'much' વપરાય છે. (મારી પાસે ઘણો સમય નથી.)" },
    { "question": "I have ___ money to buy food.", "options": ["a little", "little", "a few", "few"], "answer": "a little", "explanation": "થોડુંક છે (Positive meaning) માટે 'a little' વપરાય છે. (મારી પાસે થોડા પૈસા છે.)" },
    { "question": "There is ___ hope of success.", "options": ["little", "a little", "few", "a few"], "answer": "little", "explanation": "નહિવત (Negative meaning) માટે 'little' વપરાય છે. (સફળતાની ભાગ્યે જ આશા છે.)" },
    { "question": "I have ___ money. (હકાર)", "options": ["some", "any", "no", "none"], "answer": "some", "explanation": "હકાર વાક્યમાં 'some' વપરાય છે. (મારી પાસે થોડા પૈસા છે.)" },
    { "question": "Do you have ___ pen?", "options": ["any", "some", "no", "none"], "answer": "any", "explanation": "પ્રશ્નાર્થ વાક્યમાં 'any' વપરાય છે. (તમારી પાસે કોઈ પેન છે?)" },
    { "question": "___ is at the door.", "options": ["Someone", "Anyone", "No one", "Everyone"], "answer": "Someone", "explanation": "હકાર વાક્યમાં 'Someone' વપરાય છે. (દરવાજે કોઈક છે.)" }
  ],
  "test-4": [
    { "question": "___ came to help me.", "options": ["Nobody", "Somebody", "Everybody", "Anybody"], "answer": "Nobody", "explanation": "કોઈ નહીં માટે 'Nobody' વપરાય છે. (કોઈ મદદ કરવા ન આવ્યું.)" },
    { "question": "___ students are present.", "options": ["All", "Some", "Any", "None"], "answer": "All", "explanation": "બધા માટે 'All' વપરાય છે. (બધા વિદ્યાર્થીઓ હાજર છે.)" },
    { "question": "___ of the students was given a prize.", "options": ["Each", "Every", "All", "Some"], "answer": "Each", "explanation": "'Each' પછી singular verb (was) આવે છે. (દરેક વિદ્યાર્થીને ઇનામ અપાયું.)" },
    { "question": "You can take ___ road. (બેમાંથી એક)", "options": ["either", "neither", "each", "both"], "answer": "either", "explanation": "બેમાંથી એક (હકાર) માટે 'either' વપરાય છે. (તમે કોઈ પણ રસ્તો લઈ શકો.)" },
    { "question": "___ of the keys opens the door.", "options": ["Neither", "Either", "Both", "Each"], "answer": "Neither", "explanation": "બેમાંથી એકેય નહીં (નકાર) માટે 'Neither' વપરાય છે. (કોઈ ચાવી દરવાજો ખોલતી નથી.)" },
    { "question": "Ram and Sita love ___.", "options": ["each other", "one another", "themselves", "themself"], "answer": "each other", "explanation": "બે વ્યક્તિ વચ્ચે 'each other' વપરાય છે. (રામ અને સીતા એકબીજાને પ્રેમ કરે છે.)" },
    { "question": "The villagers helped ___.", "options": ["one another", "each other", "themselves", "themself"], "answer": "one another", "explanation": "બેથી વધુ વ્યક્તિ વચ્ચે 'one another' વપરાય છે. (ગ્રામજનોએ એકબીજાને મદદ કરી.)" },
    { "question": "This is ___ pen ___ mine.", "options": ["the same...as", "such...as", "the same...that", "such...that"], "answer": "the same...as", "explanation": "સરખાપણું દર્શાવવા 'the same...as' વપરાય છે. (આ એ જ પેન છે જે મારી છે.)" },
    { "question": "Avoid ___ friends ___ are lazy.", "options": ["such...as", "the same...as", "such...that", "the same...that"], "answer": "such...as", "explanation": "'એવા...જે' માટે 'such...as' વપરાય છે. (એવા મિત્રોથી દૂર રહો જે આળસુ હોય.)" },
    { "question": "I have two pens. One is red, ___ is blue.", "options": ["the other", "another", "other", "others"], "answer": "the other", "explanation": "બેમાંથી બીજા માટે 'the other' વપરાય છે. (એક લાલ છે, બીજી વાદળી છે.)" }
  ],
  "test-5": [
    { "question": "___ am a student.", "options": ["I", "Me", "My", "Mine"], "answer": "I", "explanation": "કર્તા (Subject) માટે 'I' વપરાય છે. (હું વિદ્યાર્થી છું.)" },
    { "question": "Give the book to ___.", "options": ["me", "I", "my", "mine"], "answer": "me", "explanation": "Preposition (to) પછી Object form 'me' વપરાય છે. (મને પુસ્તક આપો.)" },
    { "question": "This is ___ pen.", "options": ["my", "I", "me", "mine"], "answer": "my", "explanation": "Noun પહેલાં Possessive Adjective 'my' વપરાય છે. (આ મારી પેન છે.)" },
    { "question": "This pen is ___.", "options": ["mine", "my", "I", "me"], "answer": "mine", "explanation": "Noun વિના Possessive Pronoun 'mine' વપરાય છે. (આ પેન મારી છે.)" },
    { "question": "I did the work ___.", "options": ["myself", "me", "I", "my"], "answer": "myself", "explanation": "જાતે કર્યું દર્શાવવા Reflexive 'myself' વપરાય છે. (મેં કામ જાતે કર્યું.)" },
    { "question": "___ are my friends.", "options": ["They", "Them", "Their", "Theirs"], "answer": "They", "explanation": "કર્તા માટે 'They' વપરાય છે. (તેઓ મારા મિત્રો છે.)" },
    { "question": "I saw ___ at the market.", "options": ["them", "they", "their", "theirs"], "answer": "them", "explanation": "Object માટે 'them' વપરાય છે. (મેં તેમને બજારમાં જોયા.)" },
    { "question": "This is ___ house.", "options": ["their", "they", "them", "theirs"], "answer": "their", "explanation": "Noun પહેલાં 'their' વપરાય છે. (આ તેમનું ઘર છે.)" },
    { "question": "This house is ___.", "options": ["theirs", "their", "they", "them"], "answer": "theirs", "explanation": "Noun વિના 'theirs' વપરાય છે. (આ ઘર તેમનું છે.)" },
    { "question": "They taught ___ how to code.", "options": ["themselves", "them", "their", "theirs"], "answer": "themselves", "explanation": "જાતે શીખ્યા માટે Reflexive 'themselves' વપરાય છે. (તેઓએ જાતે coding શીખ્યું.)" }
  ],
  "test-6": [
    { "question": "___ is coming?", "options": ["Who", "Whom", "Whose", "Which"], "answer": "Who", "explanation": "ખાલી પછી verb હોય તો 'Who' આવે. (કોણ આવે છે?)" },
    { "question": "___ did you meet?", "options": ["Whom", "Who", "Whose", "Which"], "answer": "Whom", "explanation": "ખાલી પછી subject હોય તો 'Whom' આવે. (તમે કોને મળ્યા?)" },
    { "question": "I have ___ friends. (Countable, નકાર)", "options": ["few", "a few", "little", "a little"], "answer": "few", "explanation": "Countable + Negative meaning = 'few'. (મારે ભાગ્યે જ મિત્રો છે.)" },
    { "question": "I have ___ time. (Uncountable, નકાર)", "options": ["little", "a little", "few", "a few"], "answer": "little", "explanation": "Uncountable + Negative meaning = 'little'. (મારી પાસે ઓછો સમય છે.)" },
    { "question": "The dog wagged ___ tail.", "options": ["its", "it's", "his", "their"], "answer": "its", "explanation": "'its' = Possessive. 'it's' = it is. (કૂતરાએ તેની પૂંછડી હલાવી.)" },
    { "question": "___ raining outside.", "options": ["It's", "Its", "It", "They're"], "answer": "It's", "explanation": "'It's' = It is. (બહાર વરસાદ પડી રહ્યો છે.)" },
    { "question": "___ house is very big.", "options": ["Their", "There", "They're", "Theirs"], "answer": "Their", "explanation": "'Their' = Possessive. (તેમનું ઘર ખૂબ મોટું છે.)" },
    { "question": "The book is ___.", "options": ["there", "their", "they're", "theirs"], "answer": "there", "explanation": "'There' = Place (ત્યાં). (પુસ્તક ત્યાં છે.)" },
    { "question": "___ coming to the party.", "options": ["They're", "Their", "There", "Theirs"], "answer": "They're", "explanation": "'They're' = They are. (તેઓ પાર્ટીમાં આવી રહ્યા છે.)" },
    { "question": "Is this ___ bag?", "options": ["your", "you're", "yours", "you"], "answer": "your", "explanation": "'Your' = Possessive Adjective. (શું આ તમારી બેગ છે?)" }
  ],
  "test-7": [
    { "question": "___ a good student.", "options": ["You're", "Your", "Yours", "You"], "answer": "You're", "explanation": "'You're' = You are. (તમે સારા વિદ્યાર્થી છો.)" },
    { "question": "___ book is this?", "options": ["Whose", "Who's", "Whom", "Who"], "answer": "Whose", "explanation": "'Whose' = Possessive. (આ કોનું પુસ્તક છે?)" },
    { "question": "___ at the door?", "options": ["Who's", "Whose", "Whom", "Who"], "answer": "Who's", "explanation": "'Who's' = Who is. (દરવાજે કોણ છે?)" },
    { "question": "Ram and ___ went to market.", "options": ["I", "me", "my", "myself"], "answer": "I", "explanation": "Compound Subject માં 'I' વપરાય, 'me' નહીં. (રામ અને હું બજાર ગયા.)" },
    { "question": "She is taller than ___.", "options": ["he", "him", "his", "himself"], "answer": "he", "explanation": "Than પછી Subject form (he) આવે. (તે, તેના કરતાં ઊંચી છે.)" },
    { "question": "I run as fast as ___.", "options": ["she", "her", "hers", "herself"], "answer": "she", "explanation": "As...as પછી Subject form (she) આવે. (હું તેના જેટલી ઝડપથી દોડું છું.)" },
    { "question": "Would you like ___ tea?", "options": ["some", "any", "no", "none"], "answer": "some", "explanation": "Request/Offer માં 'some' વપરાય છે. (શું તમે ચા લેશો?)" },
    { "question": "___ road leads to the city.", "options": ["Either", "Neither", "Both", "None"], "answer": "Either", "explanation": "બેમાંથી કોઈ એક (હકાર) માટે 'Either'. (કોઈ પણ રસ્તો શહેર તરફ જાય છે.)" },
    { "question": "___ answer is correct.", "options": ["Neither", "Either", "Both", "Each"], "answer": "Neither", "explanation": "બેમાંથી એકેય નહીં (નકાર) માટે 'Neither'. (કોઈ જવાબ સાચો નથી.)" },
    { "question": "The man ___ came is my father.", "options": ["who", "which", "whom", "whose"], "answer": "who", "explanation": "વ્યક્તિ માટે Subject position માં 'who' વપરાય. (જે માણસ આવ્યો તે મારા પિતા છે.)" }
  ],
  "test-8": [
    { "question": "The book ___ I bought is good.", "options": ["which", "who", "whom", "whose"], "answer": "which", "explanation": "વસ્તુ/પ્રાણી માટે 'which' વપરાય. (જે પુસ્તક મેં ખરીદ્યું તે સારું છે.)" },
    { "question": "This is the best ___ I have.", "options": ["that", "which", "who", "whom"], "answer": "that", "explanation": "Superlative/All/None પછી 'that' વપરાય. (આ સૌથી સારું છે જે મારી પાસે છે.)" },
    { "question": "___ of the two options is better?", "options": ["Which", "What", "Who", "Whose"], "answer": "Which", "explanation": "મર્યાદિત વિકલ્પોમાંથી પસંદગી માટે 'Which' વપરાય. (બે વિકલ્પોમાંથી કયો સારો છે?)" },
    { "question": "___ is your name?", "options": ["What", "Which", "Who", "Whose"], "answer": "What", "explanation": "માહિતી પૂછવા માટે 'What' વપરાય. (તમારું નામ શું છે?)" },
    { "question": "The girl ___ I met is my cousin.", "options": ["whom", "who", "whose", "which"], "answer": "whom", "explanation": "Object position માં 'whom' વપરાય. (જે છોકરીને હું મળ્યો તે મારી બહેન છે.)" },
    { "question": "___ book I have are old.", "options": ["The few", "A few", "Few", "The little"], "answer": "The few", "explanation": "થોડું પણ બધું જ (Definite) માટે 'The few' વપરાય. (મારી પાસે જે થોડાં પુસ્તકો છે તે જૂનાં છે.)" },
    { "question": "___ water we had was finished.", "options": ["The little", "A little", "Little", "The few"], "answer": "The little", "explanation": "Uncountable + Definite માટે 'The little' વપરાય. (જે થોડું પાણી હતું તે ખતમ થઈ ગયું.)" },
    { "question": "He gave the book to my friend and ___.", "options": ["me", "I", "my", "mine"], "answer": "me", "explanation": "'To' પછી Object form 'me' આવે. (તેણે મારા મિત્ર અને મને પુસ્તક આપ્યું.)" },
    { "question": "Between you and ___, this is wrong.", "options": ["me", "I", "my", "mine"], "answer": "me", "explanation": "'Between' પછી Object form 'me' આવે. (તારા અને મારા વચ્ચે, આ ખોટું છે.)" },
    { "question": "Let you and ___ try this.", "options": ["me", "I", "my", "mine"], "answer": "me", "explanation": "'Let' પછી Object form 'me' આવે. (ચાલ તું અને હું આ અજમાવીએ.)" }
  ],
  "test-9": [
    { "question": "All of ___ need to work.", "options": ["us", "we", "our", "ours"], "answer": "us", "explanation": "'All of' પછી Object form 'us' આવે. (આપણે બધાએ કામ કરવું પડશે.)" },
    { "question": "Everyone except ___ was present.", "options": ["him", "he", "his", "himself"], "answer": "him", "explanation": "'Except' પછી Object form 'him' આવે. (તેના સિવાય બધા હાજર હતા.)" },
    { "question": "The cat hurt ___ when it jumped.", "options": ["itself", "it", "its", "it's"], "answer": "itself", "explanation": "Reflexive Pronoun 'itself' વપરાય. (બિલાડીએ કૂદતાં પોતાને ઈજા પહોંચાડી.)" },
    { "question": "She is proud of ___.", "options": ["herself", "her", "she", "hers"], "answer": "herself", "explanation": "Reflexive Pronoun 'herself' વપરાય. (તે પોતાના પર ગર્વ અનુભવે છે.)" },
    { "question": "We enjoyed ___ at the party.", "options": ["ourselves", "us", "we", "our"], "answer": "ourselves", "explanation": "Reflexive 'ourselves' વપરાય. (અમે પાર્ટીમાં મજા કરી.)" },
    { "question": "The children hid ___.", "options": ["themselves", "them", "their", "theirs"], "answer": "themselves", "explanation": "Reflexive 'themselves' વપરાય. (બાળકો સંતાઈ ગયા.)" },
    { "question": "___ is your pen.", "options": ["This", "These", "Those", "Them"], "answer": "This", "explanation": "નજીકની એકવચન વસ્તુ માટે 'This' વપરાય. (આ તમારી પેન છે.)" },
    { "question": "___ are my books.", "options": ["These", "This", "That", "Those"], "answer": "These", "explanation": "નજીકની બહુવચન વસ્તુઓ માટે 'These' વપરાય. (આ મારાં પુસ્તકો છે.)" },
    { "question": "___ is his house.", "options": ["That", "Those", "These", "This"], "answer": "That", "explanation": "દૂરની એકવચન વસ્તુ માટે 'That' વપરાય. (તે તેનું ઘર છે.)" },
    { "question": "___ are stars.", "options": ["Those", "That", "This", "These"], "answer": "Those", "explanation": "દૂરની બહુવચન વસ્તુઓ માટે 'Those' વપરાય. (તે તારાઓ છે.)" }
  ],
  "test-10": [
    { "question": "___ is she?", "options": ["Who", "What", "Which", "Whose"], "answer": "Who", "explanation": "વ્યક્તિની ઓળખ પૂછવા 'Who' વપરાય. (તે કોણ છે?)" },
    { "question": "___ is he doing?", "options": ["What", "Who", "Which", "Whose"], "answer": "What", "explanation": "ક્રિયા/કામ પૂછવા 'What' વપરાય. (તે શું કરી રહ્યો છે?)" },
    { "question": "___ bag do you want? (ત્રણમાંથી)", "options": ["Which", "What", "Who", "Whose"], "answer": "Which", "explanation": "મર્યાદિત વિકલ્પોમાંથી પસંદગી માટે 'Which'. (કઈ બેગ જોઈએ?)" },
    { "question": "___ do you think she is?", "options": ["Who", "Whom", "What", "Which"], "answer": "Who", "explanation": "Subject position માં 'Who' વપરાય. (તમને લાગે છે તે કોણ છે?)" },
    { "question": "With ___ did you go?", "options": ["whom", "who", "whose", "which"], "answer": "whom", "explanation": "'With' (Preposition) પછી 'whom' આવે. (તમે કોની સાથે ગયા?)" },
    { "question": "She and ___ are colleagues.", "options": ["I", "me", "my", "mine"], "answer": "I", "explanation": "Compound Subject માં 'I' વપરાય. (તે અને હું સહકર્મીઓ છીએ.)" },
    { "question": "Nobody was there except you and ___.", "options": ["me", "I", "my", "mine"], "answer": "me", "explanation": "'Except' પછી Object form 'me' આવે. (તમારા અને મારા સિવાય કોઈ ન હતું.)" },
    { "question": "___ of you can answer this.", "options": ["Any", "Some", "Few", "Little"], "answer": "Any", "explanation": "કોઈપણ એક માટે 'Any' વપરાય. (તમારામાંથી કોઈ પણ જવાબ આપી શકે.)" },
    { "question": "___ wants to go home early.", "options": ["Everyone", "Anyone", "Someone", "No one"], "answer": "Everyone", "explanation": "બધા માટે 'Everyone' વપરાય. (બધા વહેલા ઘરે જવા માંગે છે.)" },
    { "question": "___ knows the answer.", "options": ["No one", "Everyone", "Someone", "Anyone"], "answer": "No one", "explanation": "કોઈ નહીં માટે 'No one' વપરાય. (કોઈને જવાબ ખબર નથી.)" }
  ],
  "test-11": [
    {"question": "___ of the answers is correct.", "options": ["None", "Any", "Some", "All"], "answer": "None", "explanation": "કોઈ પણ નહીં માટે 'None' વપરાય. (કોઈ જવાબ સાચો નથી.)"},
    {"question": "___ child was given a gift.", "options": ["Each", "Every", "All", "Any"], "answer": "Each", "explanation": "દરેકને અલગ-અલગ માટે 'Each' + singular. (દરેક બાળકને ભેટ અપાઈ.)"},
    {"question": "___ student must obey the rules.", "options": ["Every", "Each", "All", "Any"], "answer": "Every", "explanation": "સમૂહમાં બધા માટે 'Every' + singular. (દરેક વિદ્યાર્થીએ નિયમો પાળવા જોઈએ.)"},
    {"question": "I have two sisters. ___ are doctors.", "options": ["Both", "Each", "Either", "Neither"], "answer": "Both", "explanation": "બંને માટે 'Both' + plural. (બંને ડૉક્ટર છે.)"},
    {"question": "You may take ___ book. (કોઈ પણ એક)", "options": ["any", "some", "every", "each"], "answer": "any", "explanation": "કોઈ પણ એક માટે 'any'. (કોઈ પણ પુસ્તક લઈ શકો.)"},
    {"question": "There is ___ milk in the bottle. (થોડુંક)", "options": ["some", "any", "no", "none"], "answer": "some", "explanation": "હકાર + Uncountable માટે 'some'. (બોટલમાં થોડું દૂધ છે.)"},
    {"question": "Is there ___ water left?", "options": ["any", "some", "no", "none"], "answer": "any", "explanation": "પ્રશ્ન વાક્યમાં 'any' વપરાય. (શું કોઈ પાણી બાકી છે?)"},
    {"question": "___ helped me in my need.", "options": ["Nobody", "Somebody", "Everybody", "Anybody"], "answer": "Nobody", "explanation": "કોઈ નહીં માટે 'Nobody'. (મારી જરૂરમાં કોઈએ મદદ ન કરી.)"},
    {"question": "___ is knocking at the door.", "options": ["Somebody", "Nobody", "Anybody", "Everybody"], "answer": "Somebody", "explanation": "કોઈક (હકાર) માટે 'Somebody'. (દરવાજે કોઈક ટકોરા મારે છે.)"},
    {"question": "___ present here knows English.", "options": ["Everybody", "Somebody", "Nobody", "Anybody"], "answer": "Everybody", "explanation": "બધા માટે 'Everybody'. (અહીં હાજર બધા ઇંગ્લિશ જાણે છે.)"}
  ],
  "test-12": [
    {"question": "I don't have ___ to say.", "options": ["anything", "something", "nothing", "everything"], "answer": "anything", "explanation": "નકાર વાક્યમાં 'anything' વપરાય. (મારે કંઈ કહેવું નથી.)"},
    {"question": "___ happens for a reason.", "options": ["Everything", "Something", "Anything", "Nothing"], "answer": "Everything", "explanation": "બધું માટે 'Everything'. (બધું કોઈ કારણસર થાય છે.)"},
    {"question": "She told me ___. (કંઈક)", "options": ["something", "anything", "nothing", "everything"], "answer": "something", "explanation": "કંઈક (હકાર) માટે 'something'. (તેણે મને કંઈક કહ્યું.)"},
    {"question": "I know ___ about this matter.", "options": ["nothing", "something", "anything", "everything"], "answer": "nothing", "explanation": "કંઈ નહીં માટે 'nothing'. (મને આ બાબતમાં કંઈ ખબર નથી.)"},
    {"question": "___ of these pens is good.", "options": ["One", "Some", "Any", "All"], "answer": "One", "explanation": "એક (નિર્દિષ્ટ) માટે 'One'. (આમાંથી એક પેન સારી છે.)"},
    {"question": "I don't like this shirt. Show me ___.", "options": ["another", "other", "the other", "others"], "answer": "another", "explanation": "અન્ય એક (અનિર્દિષ્ટ) માટે 'another'. (બીજું બતાવો.)"},
    {"question": "Some are good, ___ are bad.", "options": ["others", "another", "the other", "other"], "answer": "others", "explanation": "બાકીના (બહુવચન) માટે 'others'. (કેટલાક સારા છે, બીજા ખરાબ.)"},
    {"question": "There are two boys. One is tall, ___ is short.", "options": ["the other", "another", "other", "others"], "answer": "the other", "explanation": "બેમાંથી બીજો (નિર્દિષ્ટ) માટે 'the other'. (એક ઊંચો છે, બીજો નીચો.)"},
    {"question": "___ side of the river is green.", "options": ["The other", "Another", "Other", "Others"], "answer": "The other", "explanation": "બે બાજુમાંથી બીજી માટે 'The other'. (નદીની બીજી બાજુ લીલી છે.)"},
    {"question": "We should help ___. (એકબીજાને - 2 જણ)", "options": ["each other", "one another", "ourselves", "themselves"], "answer": "each other", "explanation": "બે વ્યક્તિ વચ્ચે 'each other'. (આપણે એકબીજાને મદદ કરવી જોઈએ.)"}
  ],
  "test-13": [
    {"question": "The students discuss ___. (એકબીજા સાથે - ઘણા)", "options": ["one another", "each other", "themselves", "themself"], "answer": "one another", "explanation": "2 થી વધુ વ્યક્તિ વચ્ચે 'one another'. (વિદ્યાર્થીઓ ચર્ચા કરે છે.)"},
    {"question": "The woman ___ son won the prize is happy.", "options": ["whose", "who", "whom", "which"], "answer": "whose", "explanation": "માલિકી દર્શાવવા 'whose'. (જે સ્ત્રીનો દીકરો જીત્યો તે ખુશ છે.)"},
    {"question": "The person ___ I admire is my teacher.", "options": ["whom", "who", "whose", "which"], "answer": "whom", "explanation": "Object position માં 'whom'. (જેની હું પ્રશંસા કરું છું તે મારા શિક્ષક છે.)"},
    {"question": "The house ___ we bought is old.", "options": ["which", "who", "whom", "whose"], "answer": "which", "explanation": "વસ્તુ માટે 'which'. (જે ઘર અમે ખરીદ્યું તે જૂનું છે.)"},
    {"question": "He is the only man ___ can do this.", "options": ["that", "who", "which", "whom"], "answer": "that", "explanation": "Only/Same/Very પછી 'that' વપરાય. (તે એકમાત્ર માણસ છે જે આ કરી શકે.)"},
    {"question": "All ___ glitters is not gold.", "options": ["that", "which", "who", "what"], "answer": "that", "explanation": "All પછી 'that' વપરાય. (બધું જે ચમકે તે સોનું નથી.)"},
    {"question": "The day ___ he arrived was rainy.", "options": ["when", "which", "that", "where"], "answer": "when", "explanation": "સમય માટે 'when'. (જે દિવસે તે આવ્યો ત્યારે વરસાદ હતો.)"},
    {"question": "The place ___ I grew up is beautiful.", "options": ["where", "which", "that", "when"], "answer": "where", "explanation": "સ્થળ માટે 'where'. (જ્યાં હું મોટો થયો તે સુંદર છે.)"},
    {"question": "I don't know ___ she said.", "options": ["what", "which", "that", "who"], "answer": "what", "explanation": "'the thing which' ના અર્થમાં 'what'. (મને ખબર નથી તેણે શું કહ્યું.)"},
    {"question": "___ you say is true.", "options": ["What", "Which", "That", "Who"], "answer": "What", "explanation": "'the thing which' ના અર્થમાં 'What'. (તમે જે કહો છો તે સાચું છે.)"}
  ],
  "test-14": [
    {"question": "___ is my sister. (નજીક)", "options": ["This", "That", "These", "Those"], "answer": "This", "explanation": "નજીકની એકવચન માટે 'This'. (આ મારી બહેન છે.)"},
    {"question": "___ are my friends. (નજીક)", "options": ["These", "Those", "This", "That"], "answer": "These", "explanation": "નજીકની બહુવચન માટે 'These'. (આ મારા મિત્રો છે.)"},
    {"question": "___ is his office. (દૂર)", "options": ["That", "This", "These", "Those"], "answer": "That", "explanation": "દૂરની એકવચન માટે 'That'. (તે તેની ઓફિસ છે.)"},
    {"question": "___ are clouds. (દૂર)", "options": ["Those", "These", "This", "That"], "answer": "Those", "explanation": "દૂરની બહુવચન માટે 'Those'. (તે વાદળો છે.)"},
    {"question": "___ is a nice day!", "options": ["What", "How", "Which", "Who"], "answer": "What", "explanation": "Noun પહેલાં 'What' = ઉદ્ગાર. (કેવો સરસ દિવસ!)"},
    {"question": "___ beautiful she is!", "options": ["How", "What", "Which", "Who"], "answer": "How", "explanation": "Adjective પહેલાં 'How' = ઉદ્ગાર. (તે કેટલી સુંદર છે!)"},
    {"question": "He introduced ___.", "options": ["himself", "him", "he", "his"], "answer": "himself", "explanation": "Reflexive 'himself'. (તેણે પોતાનો પરિચય આપ્યો.)"},
    {"question": "She hurt ___ while cooking.", "options": ["herself", "her", "she", "hers"], "answer": "herself", "explanation": "Reflexive 'herself'. (તે રસોઈ કરતાં ઘવાઈ.)"},
    {"question": "We enjoyed ___ at the picnic.", "options": ["ourselves", "us", "we", "our"], "answer": "ourselves", "explanation": "Reflexive 'ourselves'. (અમે પિકનિકમાં મજા કરી.)"},
    {"question": "The machine turned ___ off.", "options": ["itself", "it", "its", "it's"], "answer": "itself", "explanation": "Reflexive 'itself'. (મશીન આપોઆપ બંધ થઈ ગયું.)"}
  ],
  "test-15": [
    {"question": "He completed the work ___.", "options": ["himself", "herself", "myself", "yourself"], "answer": "himself", "explanation": "ભાર (Emphasis) આપવા 'himself'. (તેણે જાતે કામ પૂરું કર્યું.)"},
    {"question": "You ___ told me this.", "options": ["yourself", "myself", "himself", "herself"], "answer": "yourself", "explanation": "ભાર આપવા 'yourself'. (તમે જ મને આ કહ્યું.)"},
    {"question": "I ___ will do it.", "options": ["myself", "yourself", "himself", "herself"], "answer": "myself", "explanation": "ભાર આપવા 'myself'. (હું જ આ કરીશ.)"},
    {"question": "The queen ___ came to see us.", "options": ["herself", "himself", "myself", "yourself"], "answer": "herself", "explanation": "ભાર આપવા 'herself'. (રાણી પોતે અમને મળવા આવ્યા.)"},
    {"question": "He is taller than ___.", "options": ["I", "me", "my", "mine"], "answer": "I", "explanation": "Than પછી Subject form (I) આવે. (તે મારાથી ઊંચો છે.)"},
    {"question": "She runs faster than ___.", "options": ["he", "him", "his", "himself"], "answer": "he", "explanation": "Than પછી Subject form (he) આવે. (તે તેના કરતાં ઝડપથી દોડે છે.)"},
    {"question": "I am as tall as ___.", "options": ["he", "him", "his", "himself"], "answer": "he", "explanation": "As...as પછી Subject form આવે. (હું તેના જેટલો ઊંચો છું.)"},
    {"question": "___ and Ram went to school.", "options": ["I", "Me", "My", "Mine"], "answer": "I", "explanation": "Compound Subject માં 'I' વપરાય. (હું અને રામ સ્કૂલ ગયા.)"},
    {"question": "The teacher called Sita and ___.", "options": ["me", "I", "my", "mine"], "answer": "me", "explanation": "Object position માં 'me' આવે. (શિક્ષકે સીતા અને મને બોલાવ્યા.)"},
    {"question": "It is ___.", "options": ["I", "me", "my", "mine"], "answer": "I", "explanation": "Formal English માં 'It is I' સાચું છે. (તે હું છું.)"}
  ],
  "test-16": [
    {"question": "___ did you invite to the party?", "options": ["Whom", "Who", "Whose", "Which"], "answer": "Whom", "explanation": "Object position માં 'Whom'. (તમે પાર્ટીમાં કોને આમંત્રિત કર્યા?)"},
    {"question": "___ wrote this book?", "options": ["Who", "Whom", "Whose", "Which"], "answer": "Who", "explanation": "Subject position માં 'Who'. (આ પુસ્તક કોણે લખ્યું?)"},
    {"question": "___ of these two is better?", "options": ["Which", "What", "Who", "Whom"], "answer": "Which", "explanation": "મર્યાદિત વિકલ્પો માટે 'Which'. (આ બેમાંથી કયું સારું છે?)"},
    {"question": "___ is your hobby?", "options": ["What", "Which", "Who", "Whom"], "answer": "What", "explanation": "ખુલ્લો પ્રશ్ન માટે 'What'. (તમારો શોખ શું છે?)"},
    {"question": "To ___ should I address this letter?", "options": ["whom", "who", "whose", "which"], "answer": "whom", "explanation": "Preposition પછી 'whom'. (મારે આ પત્ર કોને લખવો જોઈએ?)"},
    {"question": "___ umbrella is this?", "options": ["Whose", "Who", "Whom", "Which"], "answer": "Whose", "explanation": "માલિકી માટે 'Whose'. (આ કોની છત્રી છે?)"},
    {"question": "___ is the capital of India?", "options": ["What", "Which", "Who", "Whose"], "answer": "What", "explanation": "માહિતી માટે 'What'. (ભારતની રાજધાની શું છે?)"},
    {"question": "___ did you see at the park?", "options": ["Whom", "Who", "Whose", "Which"], "answer": "Whom", "explanation": "Object position માં 'Whom'. (તમે પાર્કમાં કોને જોયું?)"},
    {"question": "___ is calling?", "options": ["Who", "Whom", "Whose", "Which"], "answer": "Who", "explanation": "Subject position માં 'Who'. (કોણ ફોન કરે છે?)"},
    {"question": "From ___ did you get this?", "options": ["whom", "who", "whose", "which"], "answer": "whom", "explanation": "Preposition પછી 'whom'. (તમે આ કોની પાસેથી મેળવ્યું?)"}
  ],
  "test-17": [
    {"question": "I have ___ sugar. (થોડીક, હકાર)", "options": ["a little", "little", "a few", "few"], "answer": "a little", "explanation": "Uncountable + Positive = 'a little'. (મારી પાસે થોડી ખાંડ છે.)"},
    {"question": "There is ___ hope. (ભાગ્યે જ)", "options": ["little", "a little", "few", "a few"], "answer": "little", "explanation": "Uncountable + Negative = 'little'. (ભાગ્યે જ આશા છે.)"},
    {"question": "I have ___ books. (થોડાક, હકાર)", "options": ["a few", "few", "a little", "little"], "answer": "a few", "explanation": "Countable + Positive = 'a few'. (મારી પાસે થોડાક પુસ્તકો છે.)"},
    {"question": "___ people attended. (ભાગ્યે જ)", "options": ["Few", "A few", "Little", "A little"], "answer": "Few", "explanation": "Countable + Negative = 'Few'. (ભાગ્યે જ લોકો આવ્યા.)"},
    {"question": "___ money I had was stolen.", "options": ["The little", "A little", "Little", "The few"], "answer": "The little", "explanation": "Definite + Uncountable = 'The little'. (જે થોડા પૈસા હતા તે ચોરાઈ ગયા.)"},
    {"question": "___ books I have are old.", "options": ["The few", "A few", "Few", "The little"], "answer": "The few", "explanation": "Definite + Countable = 'The few'. (જે થોડાં પુસ્તકો છે તે જૂનાં છે.)"},
    {"question": "Is there ___ milk left?", "options": ["any", "some", "no", "none"], "answer": "any", "explanation": "પ્રશ્ન વાક્યમાં 'any'. (શું કોઈ દૂધ બાકી છે?)"},
    {"question": "Would you like ___ coffee?", "options": ["some", "any", "no", "none"], "answer": "some", "explanation": "Offer માં 'some' વપરાય. (તમે કૉફી લેશો?)"},
    {"question": "Can I have ___ water?", "options": ["some", "any", "no", "none"], "answer": "some", "explanation": "Request માં 'some' વપરાય. (શું મને પાણી મળશે?)"},
    {"question": "I don't have ___ money.", "options": ["any", "some", "no", "none"], "answer": "any", "explanation": "નકાર વાક્યમાં 'any'. (મારી પાસે પૈસા નથી.)"}
  ],
  "test-18": [
    {"question": "He has ___ friends. (એક પણ નહીં)", "options": ["no", "any", "some", "none"], "answer": "no", "explanation": "Noun પહેલાં 'no'. (તેને કોઈ મિત્ર નથી.)"},
    {"question": "___ of them came. (એક પણ નહીં)", "options": ["None", "No", "Any", "Some"], "answer": "None", "explanation": "Of પહેલાં 'None'. (તેમાંથી કોઈ ન આવ્યું.)"},
    {"question": "___ of you may go first.", "options": ["Either", "Neither", "Both", "Each"], "answer": "Either", "explanation": "બેમાંથી કોઈ એક માટે 'Either'. (તમારામાંથી કોઈ પણ પહેલાં જઈ શકે.)"},
    {"question": "___ of the roads leads to city.", "options": ["Neither", "Either", "Both", "Each"], "answer": "Neither", "explanation": "બેમાંથી એકેય નહીં માટે 'Neither'. (કોઈ રસ્તો શહેર તરફ નથી જતો.)"},
    {"question": "___ of them are correct.", "options": ["Both", "Either", "Neither", "Each"], "answer": "Both", "explanation": "બંને માટે 'Both' + plural verb. (બંને સાચા છે.)"},
    {"question": "___ of the boys was given a book.", "options": ["Each", "Both", "Either", "Neither"], "answer": "Each", "explanation": "દરેકને અલગ માટે 'Each' + singular verb. (દરેક છોકરાને પુસ્તક અપાયું.)"},
    {"question": "The two brothers love ___.", "options": ["each other", "one another", "themselves", "themself"], "answer": "each other", "explanation": "બે વચ્ચે 'each other'. (બે ભાઈઓ એકબીજાને પ્રેમ કરે છે.)"},
    {"question": "All the team members support ___.", "options": ["one another", "each other", "themselves", "themself"], "answer": "one another", "explanation": "2 થી વધુ વચ્ચે 'one another'. (બધા સભ્યો એકબીજાને ટેકો આપે છે.)"},
    {"question": "The dog bit ___ master.", "options": ["its", "it's", "his", "their"], "answer": "its", "explanation": "પ્રાણી માટે Possessive 'its'. (કૂતરાએ પોતાના માલિકને કરડ્યો.)"},
    {"question": "___ a beautiful day!", "options": ["It's", "Its", "It", "They're"], "answer": "It's", "explanation": "'It's' = It is. (કેવો સુંદર દિવસ છે!)"}
  ],
  "test-19": [
    {"question": "___ going to the market.", "options": ["They're", "Their", "There", "Theirs"], "answer": "They're", "explanation": "'They're' = They are. (તેઓ બજાર જઈ રહ્યા છે.)"},
    {"question": "I saw ___ new car.", "options": ["their", "there", "they're", "theirs"], "answer": "their", "explanation": "Possessive 'their'. (મેં તેમની નવી કાર જોઈ.)"},
    {"question": "The keys are ___.", "options": ["there", "their", "they're", "theirs"], "answer": "there", "explanation": "Place માટે 'there'. (ચાવીઓ ત્યાં છે.)"},
    {"question": "This bag is ___.", "options": ["theirs", "their", "there", "they're"], "answer": "theirs", "explanation": "Noun વિના Possessive 'theirs'. (આ બેગ તેમની છે.)"},
    {"question": "___ a good singer.", "options": ["You're", "Your", "Yours", "You"], "answer": "You're", "explanation": "'You're' = You are. (તમે સારા ગાયક છો.)"},
    {"question": "Is this ___ book?", "options": ["your", "you're", "yours", "you"], "answer": "your", "explanation": "Noun પહેલાં Possessive Adj 'your'. (આ તમારું પુસ્તક છે?)"},
    {"question": "This book is ___.", "options": ["yours", "your", "you're", "you"], "answer": "yours", "explanation": "Noun વિના Possessive Pronoun 'yours'. (આ પુસ્તક તમારું છે.)"},
    {"question": "___ at the door?", "options": ["Who's", "Whose", "Whom", "Who"], "answer": "Who's", "explanation": "'Who's' = Who is. (દરવાજે કોણ છે?)"},
    {"question": "___ bag is this?", "options": ["Whose", "Who's", "Whom", "Who"], "answer": "Whose", "explanation": "માલિકી માટે 'Whose'. (આ કોની બેગ છે?)"},
    {"question": "Myself is Raj. (આ વાક્ય...)", "options": ["ખોટું છે", "સાચું છે", "બંને", "કોઈ નહીં"], "answer": "ખોટું છે", "explanation": "'I am Raj' અથવા 'My name is Raj' સાચું છે. Myself કર્તા તરીકે ન વપરાય.)"}
  ],
  "test-20": [
    {"question": "Me and Ram went to school. (આ વાક્ય...)", "options": ["ખોટું છે", "સાચું છે", "બંને", "કોઈ નહીં"], "answer": "ખોટું છે", "explanation": "'Ram and I went to school' સાચું છે. Compound Subject માં 'I' વપરાય.)"},
    {"question": "The teacher called Ram and ___.", "options": ["me", "I", "my", "myself"], "answer": "me", "explanation": "Object position માં 'me'. (શિક્ષકે રામ અને મને બોલાવ્યા.)"},
    {"question": "Give the book to Sita and ___.", "options": ["me", "I", "my", "myself"], "answer": "me", "explanation": "Preposition પછી Object 'me'. (સીતા અને મને પુસ્તક આપો.)"},
    {"question": "She is as smart as ___.", "options": ["I", "me", "my", "mine"], "answer": "I", "explanation": "As...as પછી Subject form 'I'. (તે મારા જેટલી હોશિયાર છે.)"},
    {"question": "Nobody knows it better than ___.", "options": ["she", "her", "hers", "herself"], "answer": "she", "explanation": "Than પછી Subject form 'she'. (કોઈ તેના કરતાં વધુ સારી રીતે જાણતું નથી.)"},
    {"question": "Let ___ go now.", "options": ["us", "we", "our", "ours"], "answer": "us", "explanation": "'Let' પછી Object form 'us'. (ચાલો આપણે જઈએ.)"},
    {"question": "All of ___ are students.", "options": ["us", "we", "our", "ours"], "answer": "us", "explanation": "'All of' પછી Object form 'us'. (આપણે બધા વિદ્યાર્થીઓ છીએ.)"},
    {"question": "Everyone except ___ was present.", "options": ["her", "she", "hers", "herself"], "answer": "her", "explanation": "'Except' પછી Object form 'her'. (તેના સિવાય બધા હાજર હતા.)"},
    {"question": "The work was done by you and ___.", "options": ["me", "I", "my", "myself"], "answer": "me", "explanation": "'By' પછી Object form 'me'. (કામ તમારા અને મારા દ્વારા થયું.)"},
    {"question": "Between you and ___, this is a secret.", "options": ["me", "I", "my", "mine"], "answer": "me", "explanation": "'Between' પછી Object form 'me'. (તમારા અને મારા વચ્ચે, આ રહસ્ય છે.)"}
  ],
  "test-21": [
    {"question": "___ is your teacher?", "options": ["Who", "Whom", "Whose", "Which"], "answer": "Who", "explanation": "Subject position માં 'Who'. (તમારા શિક્ષક કોણ છે?)"},
    {"question": "___ did the teacher scold?", "options": ["Whom", "Who", "Whose", "Which"], "answer": "Whom", "explanation": "Object position માં 'Whom'. (શિક્ષકે કોને ઠપકો આપ્યો?)"},
    {"question": "The boy ___ won is my brother.", "options": ["who", "whom", "whose", "which"], "answer": "who", "explanation": "Subject position માં 'who'. (જે છોકરો જીત્યો તે મારો ભાઈ છે.)"},
    {"question": "The man ___ car was stolen is sad.", "options": ["whose", "who", "whom", "which"], "answer": "whose", "explanation": "માલિકી માટે 'whose'. (જે માણસની કાર ચોરાઈ તે દુઃખી છે.)"},
    {"question": "This is all ___ I have.", "options": ["that", "which", "who", "whom"], "answer": "that", "explanation": "All પછી 'that' વપરાય. (મારી પાસે જે છે તે આ બધું જ છે.)"},
    {"question": "___ do you want to eat?", "options": ["What", "Which", "Who", "Whom"], "answer": "What", "explanation": "ખુલ્લો પ્રશ્ન માટે 'What'. (તમે શું ખાવા માંગો છો?)"},
    {"question": "___ shirt do you like? (બેમાંથી)", "options": ["Which", "What", "Who", "Whose"], "answer": "Which", "explanation": "મર્યાદિત વિકલ્પ માટે 'Which'. (કઈ શર્ટ ગમે છે?)"},
    {"question": "___ money do you have?", "options": ["How much", "How many", "How far", "How long"], "answer": "How much", "explanation": "Uncountable માટે 'How much'. (તમારી પાસે કેટલા પૈસા છે?)"},
    {"question": "___ books are on the table?", "options": ["How many", "How much", "How far", "How long"], "answer": "How many", "explanation": "Countable માટે 'How many'. (ટેબલ પર કેટલાં પુસ્તકો છે?)"},
    {"question": "___ will it take to reach?", "options": ["How long", "How far", "How much", "How many"], "answer": "How long", "explanation": "Duration માટે 'How long'. (પહોંચતાં કેટલો સમય લાગશે?)"}
  ],
  "test-22": [
    {"question": "___ is your house from here?", "options": ["How far", "How long", "How much", "How many"], "answer": "How far", "explanation": "Distance માટે 'How far'. (તમારું ઘર અહીંથી કેટલું દૂર છે?)"},
    {"question": "___ do you come here?", "options": ["How often", "How long", "How far", "How much"], "answer": "How often", "explanation": "Frequency માટે 'How often'. (તમે અહીં કેટલી વાર આવો છો?)"},
    {"question": "I have ___ to tell you.", "options": ["something", "anything", "nothing", "everything"], "answer": "something", "explanation": "હકાર + કંઈક માટે 'something'. (મારે તમને કંઈક કહેવું છે.)"},
    {"question": "There isn't ___ in the box.", "options": ["anything", "something", "nothing", "everything"], "answer": "anything", "explanation": "નકાર વાક્યમાં 'anything'. (બોક્સમાં કંઈ નથી.)"},
    {"question": "___ was wrong with the plan.", "options": ["Something", "Anything", "Nothing", "Everything"], "answer": "Something", "explanation": "હકાર + કંઈક માટે 'Something'. (યોજનામાં કંઈક ખોટું હતું.)"},
    {"question": "I heard ___ strange.", "options": ["something", "anything", "nothing", "everything"], "answer": "something", "explanation": "હકાર માં 'something'. (મેં કંઈક અજીબ સાંભળ્યું.)"},
    {"question": "Do you know ___ about this?", "options": ["anything", "something", "nothing", "everything"], "answer": "anything", "explanation": "પ્રશ્નમાં 'anything'. (તમને આ વિશે કંઈ ખબર છે?)"},
    {"question": "___ is possible.", "options": ["Anything", "Something", "Nothing", "Everything"], "answer": "Anything", "explanation": "કોઈ પણ વસ્તુ માટે 'Anything'. (કંઈ પણ શક્ય છે.)"},
    {"question": "I want to know ___.", "options": ["everything", "something", "anything", "nothing"], "answer": "everything", "explanation": "બધું જ માટે 'everything'. (મારે બધું જાણવું છે.)"},
    {"question": "___ is impossible for him.", "options": ["Nothing", "Something", "Anything", "Everything"], "answer": "Nothing", "explanation": "કંઈ નહીં માટે 'Nothing'. (તેના માટે કંઈ અશક્ય નથી.)"}
  ],
  "test-23": [
    {"question": "___ was at home.", "options": ["Nobody", "Somebody", "Anybody", "Everybody"], "answer": "Nobody", "explanation": "કોઈ નહીં = 'Nobody'. (કોઈ ઘરે ન હતું.)"},
    {"question": "___ can solve this problem.", "options": ["Anybody", "Nobody", "Somebody", "Everybody"], "answer": "Anybody", "explanation": "કોઈ પણ = 'Anybody'. (આ સમસ્યા કોઈ પણ ઉકેલી શકે.)"},
    {"question": "___ is waiting for you.", "options": ["Somebody", "Nobody", "Anybody", "Everybody"], "answer": "Somebody", "explanation": "કોઈક = 'Somebody'. (કોઈક તમારી રાહ જોઈ રહ્યું છે.)"},
    {"question": "___ knows the truth.", "options": ["Everybody", "Nobody", "Somebody", "Anybody"], "answer": "Everybody", "explanation": "બધા = 'Everybody'. (બધા સત્ય જાણે છે.)"},
    {"question": "Is ___ there?", "options": ["anybody", "somebody", "nobody", "everybody"], "answer": "anybody", "explanation": "પ્રશ્નમાં 'anybody'. (ત્યાં કોઈ છે?)"},
    {"question": "___ of the students passed.", "options": ["All", "Each", "Every", "Either"], "answer": "All", "explanation": "બધા + plural = 'All'. (બધા વિદ્યાર્થીઓ પાસ થયા.)"},
    {"question": "___ student has a book.", "options": ["Each", "All", "Some", "Any"], "answer": "Each", "explanation": "દરેક + singular = 'Each'. (દરેક વિદ્યાર્થી પાસે પુસ્તક છે.)"},
    {"question": "___ child must obey parents.", "options": ["Every", "Each", "All", "Some"], "answer": "Every", "explanation": "દરેક (સમૂહ) + singular = 'Every'. (દરેક બાળકે માતા-પિતાનું કહેવું માનવું જોઈએ.)"},
    {"question": "___ of us was given a task.", "options": ["Each", "Every", "All", "Both"], "answer": "Each", "explanation": "Each + singular verb. (અમાંથી દરેકને કાર્ય સોંપાયું.)"},
    {"question": "___ person in the room left.", "options": ["Every", "Each", "All", "Any"], "answer": "Every", "explanation": "Every + singular noun. (રૂમમાં દરેક વ્યક્તિ ગઈ.)"}
  ],
  "test-24": [
    {"question": "___ of the two boys is good.", "options": ["Either", "Neither", "Both", "Each"], "answer": "Either", "explanation": "બેમાંથી કોઈ એક (હકાર) = 'Either'. (બે છોકરાઓમાંથી કોઈ પણ સારો છે.)"},
    {"question": "___ of my parents is a doctor.", "options": ["Neither", "Either", "Both", "Each"], "answer": "Neither", "explanation": "બેમાંથી એકેય નહીં = 'Neither'. (મારા માતા-પિતામાંથી કોઈ ડૉક્ટર નથી.)"},
    {"question": "___ my parents are teachers.", "options": ["Both", "Either", "Neither", "Each"], "answer": "Both", "explanation": "બંને = 'Both' + plural. (મારા બંને માતા-પિતા શિક્ષક છે.)"},
    {"question": "He gave a pen to ___ of the students.", "options": ["each", "every", "both", "either"], "answer": "each", "explanation": "દરેકને અલગ = 'each'. (તેણે દરેક વિદ્યાર્થીને પેન આપી.)"},
    {"question": "___ side of the road is a park.", "options": ["Either", "Neither", "Both", "Each"], "answer": "Either", "explanation": "બેમાંથી કોઈ એક બાજુ = 'Either'. (રસ્તાની કોઈ પણ બાજુએ પાર્ક છે.)"},
    {"question": "You can take ___ bus. (બેમાંથી)", "options": ["either", "neither", "both", "any"], "answer": "either", "explanation": "બેમાંથી કોઈ એક = 'either'. (તમે કોઈ પણ બસ લઈ શકો.)"},
    {"question": "___ of the answers is wrong.", "options": ["Neither", "Either", "Both", "Each"], "answer": "Neither", "explanation": "બેમાંથી એકેય ખોટો નથી = 'Neither'. (કોઈ જવાબ ખોટો નથી.)"},
    {"question": "The husband and wife love ___.", "options": ["each other", "one another", "themselves", "themself"], "answer": "each other", "explanation": "બે વચ્ચે = 'each other'. (પતિ-પત્ની એકબીજાને પ્રેમ કરે છે.)"},
    {"question": "The classmates help ___.", "options": ["one another", "each other", "themselves", "themself"], "answer": "one another", "explanation": "2 થી વધુ વચ્ચે = 'one another'. (સહપાઠીઓ એકબીજાને મદદ કરે છે.)"},
    {"question": "We should respect ___.", "options": ["one another", "each other", "ourselves", "themselves"], "answer": "one another", "explanation": "સમૂહમાં પરસ્પર = 'one another'. (આપણે એકબીજાનો આદર કરવો જોઈએ.)"}
  ],
  "test-25": [
    {"question": "___ is the matter?", "options": ["What", "Which", "Who", "Whose"], "answer": "What", "explanation": "સમસ્યા/વાત માટે 'What'. (શું વાત છે?)"},
    {"question": "___ happened here?", "options": ["What", "Which", "Who", "Whose"], "answer": "What", "explanation": "ઘટના માટે 'What'. (અહીં શું થયું?)"},
    {"question": "___ made this mistake?", "options": ["Who", "What", "Which", "Whose"], "answer": "Who", "explanation": "વ્યક્તિ (Subject) માટે 'Who'. (આ ભૂલ કોણે કરી?)"},
    {"question": "For ___ are you waiting?", "options": ["whom", "who", "whose", "which"], "answer": "whom", "explanation": "Preposition પછી 'whom'. (તમે કોની રાહ જોઈ રહ્યા છો?)"},
    {"question": "The girl ___ dress is blue is my sister.", "options": ["whose", "who", "whom", "which"], "answer": "whose", "explanation": "માલિકી = 'whose'. (જે છોકરીનો ડ્રેસ વાદળી છે તે મારી બહેન છે.)"},
    {"question": "This is the house ___ Jack built.", "options": ["that", "who", "whom", "whose"], "answer": "that", "explanation": "વસ્તુ માટે 'that'. (આ તે ઘર છે જે જેકે બનાવ્યું.)"},
    {"question": "I like the flowers ___ are in the vase.", "options": ["which", "who", "whom", "whose"], "answer": "which", "explanation": "વસ્તુ માટે 'which'. (મને ફૂલદાનીમાં રહેલા ફૂલો ગમે છે.)"},
    {"question": "The reason ___ I called is important.", "options": ["why", "which", "that", "when"], "answer": "why", "explanation": "Reason પછી 'why'. (જે કારણસર મેં ફોન કર્યો તે મહત્વનું છે.)"},
    {"question": "The way ___ he talks is rude.", "options": ["that", "which", "who", "whom"], "answer": "that", "explanation": "Way પછી 'that' (અથવા omit). (જે રીતે તે બોલે છે તે અસભ્ય છે.)"},
    {"question": "She is the very person ___ can help you.", "options": ["that", "who", "whom", "which"], "answer": "that", "explanation": "Very/Same/Only પછી 'that'. (તે એ જ વ્યક્તિ છે જે તમને મદદ કરી શકે.)"}
  ],
  "test-26": [
    {"question": "___ am I to do?", "options": ["What", "Which", "Who", "Whose"], "answer": "What", "explanation": "ક્રિયા માટે 'What'. (મારે શું કરવું?)"},
    {"question": "___ is the time?", "options": ["What", "Which", "Who", "Whose"], "answer": "What", "explanation": "માહિતી માટે 'What'. (સમય શું થયો?)"},
    {"question": "___ is better, tea or coffee?", "options": ["Which", "What", "Who", "Whose"], "answer": "Which", "explanation": "મર્યાદિત વિકલ્પ માટે 'Which'. (ચા કે કૉફી, શું વધુ સારું?)"},
    {"question": "About ___ are you talking?", "options": ["whom", "who", "whose", "which"], "answer": "whom", "explanation": "Preposition પછી 'whom'. (તમે કોના વિશે વાત કરો છો?)"},
    {"question": "___ do you prefer, this or that?", "options": ["Which", "What", "Who", "Whom"], "answer": "Which", "explanation": "મર્યાદિત વિકલ્પ માટે 'Which'. (આ કે તે, શું પસંદ કરો?)"},
    {"question": "I have ___ friends. (ઘણા, હકાર)", "options": ["many", "much", "a little", "little"], "answer": "many", "explanation": "Countable + હકાર = 'many'. (મારા ઘણા મિત્રો છે.)"},
    {"question": "There isn't ___ time left.", "options": ["much", "many", "a few", "few"], "answer": "much", "explanation": "Uncountable + નકાર = 'much'. (વધુ સમય નથી.)"},
    {"question": "Did you see ___ birds?", "options": ["any", "some", "no", "none"], "answer": "any", "explanation": "પ્રશ્નમાં 'any'. (તમે કોઈ પક્ષીઓ જોયા?)"},
    {"question": "I saw ___ colorful birds.", "options": ["some", "any", "no", "none"], "answer": "some", "explanation": "હકારમાં 'some'. (મેં કેટલાક રંગીન પક્ષીઓ જોયા.)"},
    {"question": "There are ___ apples in the basket.", "options": ["some", "any", "no", "none"], "answer": "some", "explanation": "હકારમાં 'some'. (ટોપલીમાં કેટલાંક સફરજન છે.)"}
  ],
  "test-27": [
    {"question": "___ is hungry.", "options": ["Everyone", "Anyone", "Someone", "No one"], "answer": "Everyone", "explanation": "બધા = 'Everyone' + singular verb. (બધાને ભૂખ લાગી છે.)"},
    {"question": "Is ___ home?", "options": ["anyone", "someone", "no one", "everyone"], "answer": "anyone", "explanation": "પ્રશ્નમાં 'anyone'. (ઘરમાં કોઈ છે?)"},
    {"question": "___ left a message for you.", "options": ["Someone", "Anyone", "No one", "Everyone"], "answer": "Someone", "explanation": "કોઈક (હકાર) = 'Someone'. (કોઈકે તમારા માટે સંદેશો છોડ્યો.)"},
    {"question": "___ answered my call.", "options": ["No one", "Someone", "Anyone", "Everyone"], "answer": "No one", "explanation": "કોઈએ નહીં = 'No one'. (કોઈએ મારો ફોન ન ઉપાડ્યો.)"},
    {"question": "He talked to ___.", "options": ["himself", "him", "he", "his"], "answer": "himself", "explanation": "Reflexive = 'himself'. (તેણે પોતાની સાથે વાત કરી.)"},
    {"question": "She looked at ___ in the mirror.", "options": ["herself", "her", "she", "hers"], "answer": "herself", "explanation": "Reflexive = 'herself'. (તેણે અરીસામાં પોતાને જોયું.)"},
    {"question": "They blamed ___.", "options": ["themselves", "them", "their", "theirs"], "answer": "themselves", "explanation": "Reflexive = 'themselves'. (તેમણે પોતાને દોષ આપ્યો.)"},
    {"question": "We should believe in ___.", "options": ["ourselves", "us", "we", "our"], "answer": "ourselves", "explanation": "Reflexive = 'ourselves'. (આપણે પોતાના પર વિશ્વાસ રાખવો જોઈએ.)"},
    {"question": "You must help ___.", "options": ["yourself", "you", "your", "yours"], "answer": "yourself", "explanation": "Reflexive = 'yourself'. (તમારે પોતાની મદદ કરવી જોઈએ.)"},
    {"question": "The baby fell and hurt ___.", "options": ["itself", "it", "its", "it's"], "answer": "itself", "explanation": "Reflexive = 'itself'. (બાળક પડી ગયું અને ઘવાયું.)"}
  ],
  "test-28": [
    {"question": "I bought a new car. ___ is red.", "options": ["It", "Its", "It's", "They"], "answer": "It", "explanation": "Subject = 'It'. (મેં નવી કાર ખરીદી. તે લાલ છે.)"},
    {"question": "The bird has lost ___ way.", "options": ["its", "it's", "it", "their"], "answer": "its", "explanation": "Possessive = 'its'. (પક્ષી તેનો રસ્તો ભૂલી ગયું.)"},
    {"question": "___ raining heavily.", "options": ["It's", "Its", "It", "They're"], "answer": "It's", "explanation": "'It's' = It is. (ઝોરદાર વરસાદ પડી રહ્યો છે.)"},
    {"question": "I have two sisters. ___ names are Priya and Riya.", "options": ["Their", "They're", "There", "Theirs"], "answer": "Their", "explanation": "Possessive = 'Their'. (મારી બે બહેનો છે. તેમના નામ પ્રિયા અને રિયા છે.)"},
    {"question": "___ are my best friends.", "options": ["They", "Them", "Their", "Theirs"], "answer": "They", "explanation": "Subject = 'They'. (તેઓ મારા શ્રેષ્ઠ મિત્રો છે.)"},
    {"question": "I gave ___ my book.", "options": ["them", "they", "their", "theirs"], "answer": "them", "explanation": "Object = 'them'. (મેં તેમને મારું પુસ્તક આપ્યું.)"},
    {"question": "This book is ___.", "options": ["theirs", "their", "them", "they"], "answer": "theirs", "explanation": "Possessive Pronoun = 'theirs'. (આ પુસ્તક તેમનું છે.)"},
    {"question": "___ a good day!", "options": ["Have", "Your", "You're", "Yours"], "answer": "Have", "explanation": "'Have a good day' = સારો દિવસ જાઓ!"},
    {"question": "This is ___ pen. (મારી)", "options": ["my", "mine", "me", "I"], "answer": "my", "explanation": "Noun પહેલાં 'my'. (આ મારી પેન છે.)"},
    {"question": "This pen is ___.", "options": ["mine", "my", "me", "I"], "answer": "mine", "explanation": "Noun વિના 'mine'. (આ પેન મારી છે.)"}
  ],
  "test-29": [
    {"question": "He is ___ friend. (મારો)", "options": ["my", "mine", "me", "I"], "answer": "my", "explanation": "Noun પહેલાં Possessive Adj 'my'. (તે મારો મિત્ર છે.)"},
    {"question": "This bag is ___. (તેનું)", "options": ["his", "him", "he", "her"], "answer": "his", "explanation": "Noun વિના Possessive Pronoun 'his'. (આ બેગ તેની છે.)"},
    {"question": "___ won the race. (તેણી)", "options": ["She", "Her", "Hers", "Herself"], "answer": "She", "explanation": "Subject = 'She'. (તેણી રેસ જીતી.)"},
    {"question": "I gave ___ a gift. (તેણીને)", "options": ["her", "she", "hers", "herself"], "answer": "her", "explanation": "Object = 'her'. (મેં તેણીને ભેટ આપી.)"},
    {"question": "This is ___ book. (તેણીનું)", "options": ["her", "she", "hers", "herself"], "answer": "her", "explanation": "Noun પહેલાં Possessive Adj 'her'. (આ તેણીનું પુસ્તક છે.)"},
    {"question": "This book is ___. (તેણીનું)", "options": ["hers", "her", "she", "herself"], "answer": "hers", "explanation": "Noun વિના Possessive Pronoun 'hers'. (આ પુસ્તક તેણીનું છે.)"},
    {"question": "___ are playing cricket. (અમે)", "options": ["We", "Us", "Our", "Ours"], "answer": "We", "explanation": "Subject = 'We'. (અમે ક્રિકેટ રમી રહ્યા છીએ.)"},
    {"question": "He met ___ at the station. (અમને)", "options": ["us", "we", "our", "ours"], "answer": "us", "explanation": "Object = 'us'. (તે સ્ટેશને અમને મળ્યો.)"},
    {"question": "This is ___ school. (અમારી)", "options": ["our", "we", "us", "ours"], "answer": "our", "explanation": "Noun પહેલાં 'our'. (આ અમારી શાળા છે.)"},
    {"question": "This school is ___. (અમારી)", "options": ["ours", "our", "we", "us"], "answer": "ours", "explanation": "Noun વિના 'ours'. (આ શાળા અમારી છે.)"}
  ],
  "test-30": [
    {"question": "___ won the match. (તે)", "options": ["He", "Him", "His", "Himself"], "answer": "He", "explanation": "Subject = 'He'. (તેણે મેચ જીતી.)"},
    {"question": "I saw ___ yesterday. (તેને)", "options": ["him", "he", "his", "himself"], "answer": "him", "explanation": "Object = 'him'. (મેં ગઈકાલે તેને જોયો.)"},
    {"question": "This is ___ car. (તેની)", "options": ["his", "him", "he", "himself"], "answer": "his", "explanation": "Possessive = 'his'. (આ તેની કાર છે.)"},
    {"question": "This car is ___. (તેની)", "options": ["his", "him", "he", "himself"], "answer": "his", "explanation": "'His' = Possessive Adj અને Pronoun બંનેમાં સરખું. (આ કાર તેની છે.)"},
    {"question": "He did it ___. (જાતે)", "options": ["himself", "him", "his", "he"], "answer": "himself", "explanation": "Emphasis = 'himself'. (તેણે આ જાતે કર્યું.)"},
    {"question": "___ finished your homework?" , "options": ["Have you", "Your", "You're", "Yours"], "answer": "Have you", "explanation": "'Have you' = તમે પૂરું કર્યું?"},
    {"question": "She is taller than ___.", "options": ["I", "me", "my", "mine"], "answer": "I", "explanation": "Than પછી Subject form 'I'. (તે મારાથી ઊંચી છે.)"},
    {"question": "The prize was given to Sita and ___.", "options": ["me", "I", "my", "mine"], "answer": "me", "explanation": "Preposition પછી Object 'me'. (સીતા અને મને ઇનામ અપાયું.)"},
    {"question": "Let ___ help you.", "options": ["me", "I", "my", "mine"], "answer": "me", "explanation": "'Let' પછી Object 'me'. (મને તમને મદદ કરવા દો.)"},
    {"question": "It is ___. (હું)", "options": ["I", "me", "my", "mine"], "answer": "I", "explanation": "Formal English: 'It is I' = તે હું છું."}
  ]
};
