import { Question } from '@/components/grammar/GrammarTestRunner';

export const tests: Record<string, Question[]> = {
  "test-1": [
    { "question": "___ is calling you?", "options": ["Who", "Whom", "Whose", "Which"], "answer": "Who", "explanation": "कर्ता (Subject) जानने के लिए 'Who' का उपयोग होता है। (कौन तुम्हें बुला रहा है?)" },
    { "question": "___ did you meet yesterday?", "options": ["Whom", "Who", "Whose", "What"], "answer": "Whom", "explanation": "कर्म (Object) जानने के लिए 'Whom' का उपयोग होता है। (कल तुम किससे मिले?)" },
    { "question": "___ car is this?", "options": ["Whose", "Who", "Whom", "Which"], "answer": "Whose", "explanation": "मालिकी (Possession) जानने के लिए 'Whose' का उपयोग होता है। (यह किसकी कार है?)" },
    { "question": "___ is your favorite color?", "options": ["Which", "What", "Who", "Whose"], "answer": "Which", "explanation": "चुनाव के लिए 'Which' का उपयोग होता है। (तुम्हारा पसंदीदा रंग कौन सा है?)" },
    { "question": "___ is your father?", "options": ["What", "Who", "Which", "Whom"], "answer": "What", "explanation": "व्यवसाय जानने के लिए 'What' का उपयोग होता है। (तुम्हारे पिताजी क्या करते हैं?)" },
    { "question": "___ do you live?", "options": ["Where", "When", "Why", "How"], "answer": "Where", "explanation": "स्थान (Place) जानने के लिए 'Where' का उपयोग होता है। (तुम कहाँ रहते हो?)" },
    { "question": "___ will you come?", "options": ["When", "Where", "Why", "How"], "answer": "When", "explanation": "समय (Time) जानने के लिए 'When' का उपयोग होता है। (तुम कब आओगे?)" },
    { "question": "___ are you late?", "options": ["Why", "When", "Where", "How"], "answer": "Why", "explanation": "कारण (Reason) जानने के लिए 'Why' का उपयोग होता है। (तुम देर से क्यों आए?)" },
    { "question": "___ do you go to school?", "options": ["How", "Why", "When", "Where"], "answer": "How", "explanation": "तरीका (Manner) जानने के लिए 'How' का उपयोग होता है। (तुम स्कूल कैसे जाते हो?)" },
    { "question": "___ water do you need?", "options": ["How much", "How many", "How far", "How long"], "answer": "How much", "explanation": "Uncountable मात्रा के लिए 'How much' का उपयोग होता है। (तुम्हें कितना पानी चाहिए?)" }
  ],
  "test-2": [
    { "question": "___ students are there?", "options": ["How many", "How much", "How far", "How long"], "answer": "How many", "explanation": "Countable संख्या के लिए 'How many' का उपयोग होता है। (वहाँ कितने छात्र हैं?)" },
    { "question": "___ is the station from here?", "options": ["How far", "How long", "How much", "How many"], "answer": "How far", "explanation": "दूरी (Distance) जानने के लिए 'How far' का उपयोग होता है। (स्टेशन कितनी दूर है?)" },
    { "question": "___ will you stay here?", "options": ["How long", "How far", "How much", "How often"], "answer": "How long", "explanation": "अवधि (Duration) जानने के लिए 'How long' का उपयोग होता है। (तुम कितने समय रहोगे?)" },
    { "question": "___ do you exercise?", "options": ["How often", "How long", "How much", "How far"], "answer": "How often", "explanation": "Frequency जानने के लिए 'How often' का उपयोग होता है। (तुम कितनी बार व्यायाम करते हो?)" },
    { "question": "The man ___ is standing there is my uncle.", "options": ["who", "whom", "whose", "which"], "answer": "who", "explanation": "व्यक्ति के लिए कर्ता स्थान पर 'who' का उपयोग होता है। (जो आदमी वहाँ खड़ा है वह मेरे चाचा हैं।)" },
    { "question": "The boy ___ you helped is clever.", "options": ["whom", "who", "whose", "which"], "answer": "whom", "explanation": "व्यक्ति के लिए कर्म स्थान पर 'whom' का उपयोग होता है। (जिस लड़के की तुमने मदद की वह होशियार है।)" },
    { "question": "The girl ___ bag was lost is crying.", "options": ["whose", "who", "whom", "which"], "answer": "whose", "explanation": "मालिकी दर्शाने के लिए 'whose' का उपयोग होता है। (जिस लड़की का बैग खो गया वह रो रही है।)" },
    { "question": "The dog ___ bit me was mad.", "options": ["which", "who", "whom", "whose"], "answer": "which", "explanation": "जानवर/वस्तु के लिए 'which' का उपयोग होता है। (जिस कुत्ते ने मुझे काटा वह पागल था।)" },
    { "question": "This is the best book ___ I have ever read.", "options": ["that", "which", "who", "whom"], "answer": "that", "explanation": "Superlative के बाद 'that' का उपयोग होता है। (यह सबसे अच्छी किताब है जो मैंने पढ़ी है।)" },
    { "question": "By ___ was this book written?", "options": ["whom", "who", "whose", "which"], "answer": "whom", "explanation": "Preposition (By) के बाद 'whom' आता है। (यह किताब किसके द्वारा लिखी गई?)" }
  ],
  "test-3": [
    { "question": "The house in ___ I live is old.", "options": ["which", "who", "whom", "that"], "answer": "which", "explanation": "Preposition (in) के बाद 'which' आता है। (जिस घर में मैं रहता हूँ वह पुराना है।)" },
    { "question": "___ students passed the exam.", "options": ["Many", "Much", "A little", "Little"], "answer": "Many", "explanation": "Countable (students) के लिए 'Many' का उपयोग होता है। (बहुत छात्र पास हुए।)" },
    { "question": "I have ___ friends here.", "options": ["a few", "few", "a little", "little"], "answer": "a few", "explanation": "थोड़े पर हैं (Positive meaning) के लिए 'a few' का उपयोग होता है। (मेरे यहाँ कुछ दोस्त हैं।)" },
    { "question": "___ people came to the meeting.", "options": ["Few", "A few", "Little", "A little"], "answer": "Few", "explanation": "मुश्किल से कोई (Negative meaning) के लिए 'Few' का उपयोग होता है। (बहुत कम लोग मीटिंग में आए।)" },
    { "question": "I don't have ___ time.", "options": ["much", "many", "few", "a few"], "answer": "much", "explanation": "Uncountable (time) के लिए 'much' का उपयोग होता है। (मेरे पास ज्यादा समय नहीं है।)" },
    { "question": "I have ___ money to buy food.", "options": ["a little", "little", "a few", "few"], "answer": "a little", "explanation": "थोड़ा है (Positive meaning) के लिए 'a little' का उपयोग होता है। (मेरे पास थोड़े पैसे हैं।)" },
    { "question": "There is ___ hope of success.", "options": ["little", "a little", "few", "a few"], "answer": "little", "explanation": "नहीं के बराबर (Negative meaning) के लिए 'little' का उपयोग होता है। (सफलता की उम्मीद नहीं है।)" },
    { "question": "I have ___ money. (सकारात्मक)", "options": ["some", "any", "no", "none"], "answer": "some", "explanation": "सकारात्मक वाक्य में 'some' का उपयोग होता है। (मेरे पास कुछ पैसे हैं।)" },
    { "question": "Do you have ___ pen?", "options": ["any", "some", "no", "none"], "answer": "any", "explanation": "प्रश्न वाक्य में 'any' का उपयोग होता है। (क्या तुम्हारे पास कोई पेन है?)" },
    { "question": "___ is at the door.", "options": ["Someone", "Anyone", "No one", "Everyone"], "answer": "Someone", "explanation": "सकारात्मक वाक्य में 'Someone' का उपयोग होता है। (दरवाजे पर कोई है।)" }
  ],
  "test-4": [
    { "question": "___ came to help me.", "options": ["Nobody", "Somebody", "Everybody", "Anybody"], "answer": "Nobody", "explanation": "कोई नहीं के लिए 'Nobody' का उपयोग होता है। (कोई मदद करने नहीं आया।)" },
    { "question": "___ students are present.", "options": ["All", "Some", "Any", "None"], "answer": "All", "explanation": "सभी के लिए 'All' का उपयोग होता है। (सभी छात्र हाजिर हैं।)" },
    { "question": "___ of the students was given a prize.", "options": ["Each", "Every", "All", "Some"], "answer": "Each", "explanation": "'Each' के बाद singular verb (was) आता है। (हर छात्र को इनाम दिया गया।)" },
    { "question": "You can take ___ road. (दोनों में से एक)", "options": ["either", "neither", "each", "both"], "answer": "either", "explanation": "दोनों में से एक (सकारात्मक) के लिए 'either' का उपयोग होता है। (तुम कोई भी रास्ता ले सकते हो।)" },
    { "question": "___ of the keys opens the door.", "options": ["Neither", "Either", "Both", "Each"], "answer": "Neither", "explanation": "दोनों में से कोई नहीं (नकारात्मक) के लिए 'Neither' का उपयोग होता है। (कोई चाबी दरवाजा नहीं खोलती।)" },
    { "question": "Ram and Sita love ___.", "options": ["each other", "one another", "themselves", "themself"], "answer": "each other", "explanation": "दो व्यक्तियों के बीच 'each other' का उपयोग होता है। (राम और सीता एक-दूसरे से प्यार करते हैं।)" },
    { "question": "The villagers helped ___.", "options": ["one another", "each other", "themselves", "themself"], "answer": "one another", "explanation": "दो से अधिक व्यक्तियों के बीच 'one another' का उपयोग होता है। (गाँव वालों ने एक-दूसरे की मदद की।)" },
    { "question": "This is ___ pen ___ mine.", "options": ["the same...as", "such...as", "the same...that", "such...that"], "answer": "the same...as", "explanation": "समानता दर्शाने के लिए 'the same...as' का उपयोग होता है। (यह वही पेन है जो मेरी है।)" },
    { "question": "Avoid ___ friends ___ are lazy.", "options": ["such...as", "the same...as", "such...that", "the same...that"], "answer": "such...as", "explanation": "'ऐसे...जो' के लिए 'such...as' का उपयोग होता है। (ऐसे दोस्तों से दूर रहो जो आलसी हों।)" },
    { "question": "I have two pens. One is red, ___ is blue.", "options": ["the other", "another", "other", "others"], "answer": "the other", "explanation": "दोनों में से दूसरे के लिए 'the other' का उपयोग होता है। (एक लाल है, दूसरी नीली है।)" }
  ],
  "test-5": [
    { "question": "___ am a student.", "options": ["I", "Me", "My", "Mine"], "answer": "I", "explanation": "कर्ता (Subject) के लिए 'I' का उपयोग होता है। (मैं छात्र हूँ।)" },
    { "question": "Give the book to ___.", "options": ["me", "I", "my", "mine"], "answer": "me", "explanation": "Preposition (to) के बाद Object form 'me' आता है। (मुझे किताब दो।)" },
    { "question": "This is ___ pen.", "options": ["my", "I", "me", "mine"], "answer": "my", "explanation": "Noun से पहले Possessive Adjective 'my' आता है। (यह मेरी पेन है।)" },
    { "question": "This pen is ___.", "options": ["mine", "my", "I", "me"], "answer": "mine", "explanation": "Noun के बिना Possessive Pronoun 'mine' आता है। (यह पेन मेरी है।)" },
    { "question": "I did the work ___.", "options": ["myself", "me", "I", "my"], "answer": "myself", "explanation": "खुद किया दर्शाने के लिए Reflexive 'myself' का उपयोग होता है। (मैंने काम खुद किया।)" },
    { "question": "___ are my friends.", "options": ["They", "Them", "Their", "Theirs"], "answer": "They", "explanation": "कर्ता के लिए 'They' का उपयोग होता है। (वे मेरे दोस्त हैं।)" },
    { "question": "I saw ___ at the market.", "options": ["them", "they", "their", "theirs"], "answer": "them", "explanation": "Object के लिए 'them' का उपयोग होता है। (मैंने उन्हें बाजार में देखा।)" },
    { "question": "This is ___ house.", "options": ["their", "they", "them", "theirs"], "answer": "their", "explanation": "Noun से पहले 'their' आता है। (यह उनका घर है।)" },
    { "question": "This house is ___.", "options": ["theirs", "their", "they", "them"], "answer": "theirs", "explanation": "Noun के बिना 'theirs' आता है। (यह घर उनका है।)" },
    { "question": "They taught ___ how to code.", "options": ["themselves", "them", "their", "theirs"], "answer": "themselves", "explanation": "खुद सीखा के लिए Reflexive 'themselves' का उपयोग होता है। (उन्होंने खुद coding सीखी।)" }
  ],
  "test-6": [
    { "question": "___ is coming?", "options": ["Who", "Whom", "Whose", "Which"], "answer": "Who", "explanation": "खाली के बाद verb हो तो 'Who' आता है। (कौन आ रहा है?)" },
    { "question": "___ did you meet?", "options": ["Whom", "Who", "Whose", "Which"], "answer": "Whom", "explanation": "खाली के बाद subject हो तो 'Whom' आता है। (तुम किससे मिले?)" },
    { "question": "I have ___ friends. (Countable, नकारात्मक)", "options": ["few", "a few", "little", "a little"], "answer": "few", "explanation": "Countable + Negative meaning = 'few'। (मेरे मुश्किल से दोस्त हैं।)" },
    { "question": "I have ___ time. (Uncountable, नकारात्मक)", "options": ["little", "a little", "few", "a few"], "answer": "little", "explanation": "Uncountable + Negative meaning = 'little'। (मेरे पास कम समय है।)" },
    { "question": "The dog wagged ___ tail.", "options": ["its", "it's", "his", "their"], "answer": "its", "explanation": "'its' = Possessive। 'it's' = it is। (कुत्ते ने अपनी पूँछ हिलाई।)" },
    { "question": "___ raining outside.", "options": ["It's", "Its", "It", "They're"], "answer": "It's", "explanation": "'It's' = It is। (बाहर बारिश हो रही है।)" },
    { "question": "___ house is very big.", "options": ["Their", "There", "They're", "Theirs"], "answer": "Their", "explanation": "'Their' = Possessive। (उनका घर बहुत बड़ा है।)" },
    { "question": "The book is ___.", "options": ["there", "their", "they're", "theirs"], "answer": "there", "explanation": "'There' = Place (वहाँ)। (किताब वहाँ है।)" },
    { "question": "___ coming to the party.", "options": ["They're", "Their", "There", "Theirs"], "answer": "They're", "explanation": "'They're' = They are। (वे पार्टी में आ रहे हैं।)" },
    { "question": "Is this ___ bag?", "options": ["your", "you're", "yours", "you"], "answer": "your", "explanation": "'Your' = Possessive Adjective। (क्या यह तुम्हारा बैग है?)" }
  ],
  "test-7": [
    { "question": "___ a good student.", "options": ["You're", "Your", "Yours", "You"], "answer": "You're", "explanation": "'You're' = You are। (तुम अच्छे छात्र हो।)" },
    { "question": "___ book is this?", "options": ["Whose", "Who's", "Whom", "Who"], "answer": "Whose", "explanation": "'Whose' = Possessive। (यह किसकी किताब है?)" },
    { "question": "___ at the door?", "options": ["Who's", "Whose", "Whom", "Who"], "answer": "Who's", "explanation": "'Who's' = Who is। (दरवाजे पर कौन है?)" },
    { "question": "Ram and ___ went to market.", "options": ["I", "me", "my", "myself"], "answer": "I", "explanation": "Compound Subject में 'I' आता है, 'me' नहीं। (राम और मैं बाजार गए।)" },
    { "question": "She is taller than ___.", "options": ["he", "him", "his", "himself"], "answer": "he", "explanation": "Than के बाद Subject form (he) आता है। (वह उससे लंबी है।)" },
    { "question": "I run as fast as ___.", "options": ["she", "her", "hers", "herself"], "answer": "she", "explanation": "As...as के बाद Subject form (she) आता है। (मैं उतनी तेज दौड़ता हूँ जितनी वह।)" },
    { "question": "Would you like ___ tea?", "options": ["some", "any", "no", "none"], "answer": "some", "explanation": "Request/Offer में 'some' का उपयोग होता है। (क्या आप चाय लेंगे?)" },
    { "question": "___ road leads to the city.", "options": ["Either", "Neither", "Both", "None"], "answer": "Either", "explanation": "दोनों में से कोई एक (सकारात्मक) के लिए 'Either'। (कोई भी रास्ता शहर जाता है।)" },
    { "question": "___ answer is correct.", "options": ["Neither", "Either", "Both", "Each"], "answer": "Neither", "explanation": "दोनों में से कोई नहीं (नकारात्मक) के लिए 'Neither'। (कोई जवाब सही नहीं है।)" },
    { "question": "The man ___ came is my father.", "options": ["who", "which", "whom", "whose"], "answer": "who", "explanation": "व्यक्ति के लिए Subject position में 'who' आता है। (जो आदमी आया वह मेरे पिता हैं।)" }
  ],
  "test-8": [
    { "question": "The book ___ I bought is good.", "options": ["which", "who", "whom", "whose"], "answer": "which", "explanation": "वस्तु/जानवर के लिए 'which' आता है। (जो किताब मैंने खरीदी वह अच्छी है।)" },
    { "question": "This is the best ___ I have.", "options": ["that", "which", "who", "whom"], "answer": "that", "explanation": "Superlative/All/None के बाद 'that' आता है। (यह सबसे अच्छा है जो मेरे पास है।)" },
    { "question": "___ of the two options is better?", "options": ["Which", "What", "Who", "Whose"], "answer": "Which", "explanation": "सीमित विकल्पों में से चुनाव के लिए 'Which' आता है। (दो विकल्पों में से कौन सा बेहतर है?)" },
    { "question": "___ is your name?", "options": ["What", "Which", "Who", "Whose"], "answer": "What", "explanation": "जानकारी पूछने के लिए 'What' आता है। (तुम्हारा नाम क्या है?)" },
    { "question": "The girl ___ I met is my cousin.", "options": ["whom", "who", "whose", "which"], "answer": "whom", "explanation": "Object position में 'whom' आता है। (जिस लड़की से मैं मिला वह मेरी बहन है।)" },
    { "question": "___ book I have are old.", "options": ["The few", "A few", "Few", "The little"], "answer": "The few", "explanation": "थोड़ा पर सब (Definite) के लिए 'The few' आता है। (मेरे पास जो थोड़ी किताबें हैं वे पुरानी हैं।)" },
    { "question": "___ water we had was finished.", "options": ["The little", "A little", "Little", "The few"], "answer": "The little", "explanation": "Uncountable + Definite के लिए 'The little' आता है। (जो थोड़ा पानी था वह खत्म हो गया।)" },
    { "question": "He gave the book to my friend and ___.", "options": ["me", "I", "my", "mine"], "answer": "me", "explanation": "'To' के बाद Object form 'me' आता है। (उसने मेरे दोस्त और मुझे किताब दी।)" },
    { "question": "Between you and ___, this is wrong.", "options": ["me", "I", "my", "mine"], "answer": "me", "explanation": "'Between' के बाद Object form 'me' आता है। (तुम्हारे और मेरे बीच, यह गलत है।)" },
    { "question": "Let you and ___ try this.", "options": ["me", "I", "my", "mine"], "answer": "me", "explanation": "'Let' के बाद Object form 'me' आता है। (चलो तुम और मैं यह आजमाते हैं।)" }
  ],
  "test-9": [
    { "question": "All of ___ need to work.", "options": ["us", "we", "our", "ours"], "answer": "us", "explanation": "'All of' के बाद Object form 'us' आता है। (हम सभी को काम करना होगा।)" },
    { "question": "Everyone except ___ was present.", "options": ["him", "he", "his", "himself"], "answer": "him", "explanation": "'Except' के बाद Object form 'him' आता है। (उसके सिवाय सब हाजिर थे।)" },
    { "question": "The cat hurt ___ when it jumped.", "options": ["itself", "it", "its", "it's"], "answer": "itself", "explanation": "Reflexive Pronoun 'itself' आता है। (बिल्ली कूदते समय खुद को चोट पहुँचाई।)" },
    { "question": "She is proud of ___.", "options": ["herself", "her", "she", "hers"], "answer": "herself", "explanation": "Reflexive Pronoun 'herself' आता है। (वह खुद पर गर्व करती है।)" },
    { "question": "We enjoyed ___ at the party.", "options": ["ourselves", "us", "we", "our"], "answer": "ourselves", "explanation": "Reflexive 'ourselves' आता है। (हमने पार्टी में मजा किया।)" },
    { "question": "The children hid ___.", "options": ["themselves", "them", "their", "theirs"], "answer": "themselves", "explanation": "Reflexive 'themselves' आता है। (बच्चे छिप गए।)" },
    { "question": "___ is your pen.", "options": ["This", "These", "Those", "Them"], "answer": "This", "explanation": "नजदीक की एकवचन वस्तु के लिए 'This' आता है। (यह तुम्हारी पेन है।)" },
    { "question": "___ are my books.", "options": ["These", "This", "That", "Those"], "answer": "These", "explanation": "नजदीक की बहुवचन वस्तुओं के लिए 'These' आता है। (ये मेरी किताबें हैं।)" },
    { "question": "___ is his house.", "options": ["That", "Those", "These", "This"], "answer": "That", "explanation": "दूर की एकवचन वस्तु के लिए 'That' आता है। (वह उसका घर है।)" },
    { "question": "___ are stars.", "options": ["Those", "That", "This", "These"], "answer": "Those", "explanation": "दूर की बहुवचन वस्तुओं के लिए 'Those' आता है। (वे तारे हैं।)" }
  ],
  "test-10": [
    { "question": "___ is she?", "options": ["Who", "What", "Which", "Whose"], "answer": "Who", "explanation": "व्यक्ति की पहचान पूछने के लिए 'Who' आता है। (वह कौन है?)" },
    { "question": "___ is he doing?", "options": ["What", "Who", "Which", "Whose"], "answer": "What", "explanation": "क्रिया/काम पूछने के लिए 'What' आता है। (वह क्या कर रहा है?)" },
    { "question": "___ bag do you want? (तीन में से)", "options": ["Which", "What", "Who", "Whose"], "answer": "Which", "explanation": "सीमित विकल्पों में से चुनाव के लिए 'Which'। (कौन सा बैग चाहिए?)" },
    { "question": "___ do you think she is?", "options": ["Who", "Whom", "What", "Which"], "answer": "Who", "explanation": "Subject position में 'Who' आता है। (तुम्हें लगता है वह कौन है?)" },
    { "question": "With ___ did you go?", "options": ["whom", "who", "whose", "which"], "answer": "whom", "explanation": "'With' (Preposition) के बाद 'whom' आता है। (तुम किसके साथ गए?)" },
    { "question": "She and ___ are colleagues.", "options": ["I", "me", "my", "mine"], "answer": "I", "explanation": "Compound Subject में 'I' आता है। (वह और मैं सहकर्मी हैं।)" },
    { "question": "Nobody was there except you and ___.", "options": ["me", "I", "my", "mine"], "answer": "me", "explanation": "'Except' के बाद Object form 'me' आता है। (तुम्हारे और मेरे सिवाय कोई नहीं था।)" },
    { "question": "___ of you can answer this.", "options": ["Any", "Some", "Few", "Little"], "answer": "Any", "explanation": "कोई भी एक के लिए 'Any' आता है। (तुम में से कोई भी जवाब दे सकता है।)" },
    { "question": "___ wants to go home early.", "options": ["Everyone", "Anyone", "Someone", "No one"], "answer": "Everyone", "explanation": "सभी के लिए 'Everyone' आता है। (सब जल्दी घर जाना चाहते हैं।)" },
    { "question": "___ knows the answer.", "options": ["No one", "Everyone", "Someone", "Anyone"], "answer": "No one", "explanation": "कोई नहीं के लिए 'No one' आता है। (किसी को जवाब नहीं पता।)" }
  ],
  "test-11": [
    {"question": "___ of the answers is correct.", "options": ["None", "Any", "Some", "All"], "answer": "None", "explanation": "कोई भी नहीं के लिए 'None' आता है। (कोई जवाब सही नहीं है।)"},
    {"question": "___ child was given a gift.", "options": ["Each", "Every", "All", "Any"], "answer": "Each", "explanation": "हर एक को अलग-अलग के लिए 'Each' + singular। (हर बच्चे को तोहफा दिया गया।)"},
    {"question": "___ student must obey the rules.", "options": ["Every", "Each", "All", "Any"], "answer": "Every", "explanation": "समूह में सभी के लिए 'Every' + singular। (हर छात्र को नियम मानने चाहिए।)"},
    {"question": "I have two sisters. ___ are doctors.", "options": ["Both", "Each", "Either", "Neither"], "answer": "Both", "explanation": "दोनों के लिए 'Both' + plural। (दोनों डॉक्टर हैं।)"},
    {"question": "You may take ___ book. (कोई भी एक)", "options": ["any", "some", "every", "each"], "answer": "any", "explanation": "कोई भी एक के लिए 'any'। (कोई भी किताब ले सकते हो।)"},
    {"question": "There is ___ milk in the bottle. (थोड़ा)", "options": ["some", "any", "no", "none"], "answer": "some", "explanation": "सकारात्मक + Uncountable के लिए 'some'। (बोतल में थोड़ा दूध है।)"},
    {"question": "Is there ___ water left?", "options": ["any", "some", "no", "none"], "answer": "any", "explanation": "प्रश्न वाक्य में 'any' आता है। (क्या कोई पानी बचा है?)"},
    {"question": "___ helped me in my need.", "options": ["Nobody", "Somebody", "Everybody", "Anybody"], "answer": "Nobody", "explanation": "कोई नहीं के लिए 'Nobody'। (मेरी जरूरत में किसी ने मदद नहीं की।)"},
    {"question": "___ is knocking at the door.", "options": ["Somebody", "Nobody", "Anybody", "Everybody"], "answer": "Somebody", "explanation": "कोई (सकारात्मक) के लिए 'Somebody'। (दरवाजे पर कोई दस्तक दे रहा है।)"},
    {"question": "___ present here knows English.", "options": ["Everybody", "Somebody", "Nobody", "Anybody"], "answer": "Everybody", "explanation": "सभी के लिए 'Everybody'। (यहाँ मौजूद सभी अंग्रेजी जानते हैं।)"}
  ],
  "test-12": [
    {"question": "I don't have ___ to say.", "options": ["anything", "something", "nothing", "everything"], "answer": "anything", "explanation": "नकारात्मक वाक्य में 'anything' आता है। (मेरे पास कहने को कुछ नहीं है।)"},
    {"question": "___ happens for a reason.", "options": ["Everything", "Something", "Anything", "Nothing"], "answer": "Everything", "explanation": "सब कुछ के लिए 'Everything'। (सब कुछ किसी कारण से होता है।)"},
    {"question": "She told me ___. (कुछ)", "options": ["something", "anything", "nothing", "everything"], "answer": "something", "explanation": "कुछ (सकारात्मक) के लिए 'something'। (उसने मुझे कुछ बताया।)"},
    {"question": "I know ___ about this matter.", "options": ["nothing", "something", "anything", "everything"], "answer": "nothing", "explanation": "कुछ नहीं के लिए 'nothing'। (मुझे इस बारे में कुछ नहीं पता।)"},
    {"question": "___ of these pens is good.", "options": ["One", "Some", "Any", "All"], "answer": "One", "explanation": "एक (निर्दिष्ट) के लिए 'One'। (इनमें से एक पेन अच्छी है।)"},
    {"question": "I don't like this shirt. Show me ___.", "options": ["another", "other", "the other", "others"], "answer": "another", "explanation": "कोई और एक (अनिर्दिष्ट) के लिए 'another'। (कोई दूसरी दिखाओ।)"},
    {"question": "Some are good, ___ are bad.", "options": ["others", "another", "the other", "other"], "answer": "others", "explanation": "बाकी के (बहुवचन) के लिए 'others'। (कुछ अच्छे हैं, बाकी बुरे हैं।)"},
    {"question": "There are two boys. One is tall, ___ is short.", "options": ["the other", "another", "other", "others"], "answer": "the other", "explanation": "दोनों में से दूसरा (निर्दिष्ट) के लिए 'the other'। (एक लंबा है, दूसरा छोटा है।)"},
    {"question": "___ side of the river is green.", "options": ["The other", "Another", "Other", "Others"], "answer": "The other", "explanation": "दोनों में से दूसरी तरफ के लिए 'The other'। (नदी का दूसरा किनारा हरा है।)"},
    {"question": "We should help ___. (एक-दूसरे को - 2 लोग)", "options": ["each other", "one another", "ourselves", "themselves"], "answer": "each other", "explanation": "दो व्यक्तियों के बीच 'each other'। (हमें एक-दूसरे की मदद करनी चाहिए।)"}
  ],
  "test-13": [
    {"question": "The students discuss ___. (एक-दूसरे से - कई)", "options": ["one another", "each other", "themselves", "themself"], "answer": "one another", "explanation": "2 से अधिक व्यक्तियों के बीच 'one another'। (छात्र चर्चा करते हैं।)"},
    {"question": "The woman ___ son won the prize is happy.", "options": ["whose", "who", "whom", "which"], "answer": "whose", "explanation": "मालिकी दर्शाने के लिए 'whose'। (जिस महिला का बेटा जीता वह खुश है।)"},
    {"question": "The person ___ I admire is my teacher.", "options": ["whom", "who", "whose", "which"], "answer": "whom", "explanation": "Object position में 'whom'। (जिसकी मैं प्रशंसा करता हूँ वह मेरे शिक्षक हैं।)"},
    {"question": "The house ___ we bought is old.", "options": ["which", "who", "whom", "whose"], "answer": "which", "explanation": "वस्तु के लिए 'which'। (जो घर हमने खरीदा वह पुराना है।)"},
    {"question": "He is the only man ___ can do this.", "options": ["that", "who", "which", "whom"], "answer": "that", "explanation": "Only/Same/Very के बाद 'that' आता है। (वह एकमात्र आदमी है जो यह कर सकता है।)"},
    {"question": "All ___ glitters is not gold.", "options": ["that", "which", "who", "what"], "answer": "that", "explanation": "All के बाद 'that' आता है। (जो चमकता है वह सोना नहीं होता।)"},
    {"question": "The day ___ he arrived was rainy.", "options": ["when", "which", "that", "where"], "answer": "when", "explanation": "समय के लिए 'when'। (जिस दिन वह आया बारिश थी।)"},
    {"question": "The place ___ I grew up is beautiful.", "options": ["where", "which", "that", "when"], "answer": "where", "explanation": "स्थान के लिए 'where'। (जहाँ मैं बड़ा हुआ वह सुंदर है।)"},
    {"question": "I don't know ___ she said.", "options": ["what", "which", "that", "who"], "answer": "what", "explanation": "'the thing which' के अर्थ में 'what'। (मुझे नहीं पता उसने क्या कहा।)"},
    {"question": "___ you say is true.", "options": ["What", "Which", "That", "Who"], "answer": "What", "explanation": "'the thing which' के अर्थ में 'What'। (तुम जो कहते हो वह सच है।)"}
  ],
  "test-14": [
    {"question": "___ is my sister. (नजदीक)", "options": ["This", "That", "These", "Those"], "answer": "This", "explanation": "नजदीक की एकवचन के लिए 'This'। (यह मेरी बहन है।)"},
    {"question": "___ are my friends. (नजदीक)", "options": ["These", "Those", "This", "That"], "answer": "These", "explanation": "नजदीक की बहुवचन के लिए 'These'। (ये मेरे दोस्त हैं।)"},
    {"question": "___ is his office. (दूर)", "options": ["That", "This", "These", "Those"], "answer": "That", "explanation": "दूर की एकवचन के लिए 'That'। (वह उसका ऑफिस है।)"},
    {"question": "___ are clouds. (दूर)", "options": ["Those", "These", "This", "That"], "answer": "Those", "explanation": "दूर की बहुवचन के लिए 'Those'। (वे बादल हैं।)"},
    {"question": "___ is a nice day!", "options": ["What", "How", "Which", "Who"], "answer": "What", "explanation": "Noun से पहले 'What' = उद्गार। (क्या अच्छा दिन है!)"},
    {"question": "___ beautiful she is!", "options": ["How", "What", "Which", "Who"], "answer": "How", "explanation": "Adjective से पहले 'How' = उद्गार। (वह कितनी सुंदर है!)"},
    {"question": "He introduced ___.", "options": ["himself", "him", "he", "his"], "answer": "himself", "explanation": "Reflexive 'himself'। (उसने अपना परिचय दिया।)"},
    {"question": "She hurt ___ while cooking.", "options": ["herself", "her", "she", "hers"], "answer": "herself", "explanation": "Reflexive 'herself'। (खाना बनाते समय उसने खुद को चोट पहुँचाई।)"},
    {"question": "We enjoyed ___ at the picnic.", "options": ["ourselves", "us", "we", "our"], "answer": "ourselves", "explanation": "Reflexive 'ourselves'। (हमने पिकनिक में मजा किया।)"},
    {"question": "The machine turned ___ off.", "options": ["itself", "it", "its", "it's"], "answer": "itself", "explanation": "Reflexive 'itself'। (मशीन अपने आप बंद हो गई।)"}
  ],
  "test-15": [
    {"question": "He completed the work ___.", "options": ["himself", "herself", "myself", "yourself"], "answer": "himself", "explanation": "जोर (Emphasis) देने के लिए 'himself'। (उसने खुद काम पूरा किया।)"},
    {"question": "You ___ told me this.", "options": ["yourself", "myself", "himself", "herself"], "answer": "yourself", "explanation": "जोर देने के लिए 'yourself'। (तुमने ही मुझे यह बताया।)"},
    {"question": "I ___ will do it.", "options": ["myself", "yourself", "himself", "herself"], "answer": "myself", "explanation": "जोर देने के लिए 'myself'। (मैं खुद यह करूँगा।)"},
    {"question": "The queen ___ came to see us.", "options": ["herself", "himself", "myself", "yourself"], "answer": "herself", "explanation": "जोर देने के लिए 'herself'। (रानी खुद हमसे मिलने आई।)"},
    {"question": "He is taller than ___.", "options": ["I", "me", "my", "mine"], "answer": "I", "explanation": "Than के बाद Subject form (I) आता है। (वह मुझसे लंबा है।)"},
    {"question": "She runs faster than ___.", "options": ["he", "him", "his", "himself"], "answer": "he", "explanation": "Than के बाद Subject form (he) आता है। (वह उससे तेज दौड़ती है।)"},
    {"question": "I am as tall as ___.", "options": ["he", "him", "his", "himself"], "answer": "he", "explanation": "As...as के बाद Subject form आता है। (मैं उतना लंबा हूँ जितना वह।)"},
    {"question": "___ and Ram went to school.", "options": ["I", "Me", "My", "Mine"], "answer": "I", "explanation": "Compound Subject में 'I' आता है। (मैं और राम स्कूल गए।)"},
    {"question": "The teacher called Sita and ___.", "options": ["me", "I", "my", "mine"], "answer": "me", "explanation": "Object position में 'me' आता है। (टीचर ने सीता और मुझे बुलाया।)"},
    {"question": "It is ___.", "options": ["I", "me", "my", "mine"], "answer": "I", "explanation": "Formal English में 'It is I' सही है। (वह मैं हूँ।)"}
  ],
  "test-16": [
    {"question": "___ did you invite to the party?", "options": ["Whom", "Who", "Whose", "Which"], "answer": "Whom", "explanation": "Object position में 'Whom'। (तुमने पार्टी में किसे बुलाया?)"},
    {"question": "___ wrote this book?", "options": ["Who", "Whom", "Whose", "Which"], "answer": "Who", "explanation": "Subject position में 'Who'। (यह किताब किसने लिखी?)"},
    {"question": "___ of these two is better?", "options": ["Which", "What", "Who", "Whom"], "answer": "Which", "explanation": "सीमित विकल्पों में से चुनाव के लिए 'Which'। (इन दोनों में से कौन बेहतर है?)"},
    {"question": "___ is your hobby?", "options": ["What", "Which", "Who", "Whom"], "answer": "What", "explanation": "खुला प्रश्न के लिए 'What'। (तुम्हारा शौक क्या है?)"},
    {"question": "To ___ should I address this letter?", "options": ["whom", "who", "whose", "which"], "answer": "whom", "explanation": "Preposition के बाद 'whom'। (मुझे यह पत्र किसे लिखना चाहिए?)"},
    {"question": "___ umbrella is this?", "options": ["Whose", "Who", "Whom", "Which"], "answer": "Whose", "explanation": "मालिकी के लिए 'Whose'। (यह किसकी छतरी है?)"},
    {"question": "___ is the capital of India?", "options": ["What", "Which", "Who", "Whose"], "answer": "What", "explanation": "जानकारी के लिए 'What'। (भारत की राजधानी क्या है?)"},
    {"question": "___ did you see at the park?", "options": ["Whom", "Who", "Whose", "Which"], "answer": "Whom", "explanation": "Object position में 'Whom'। (तुमने पार्क में किसे देखा?)"},
    {"question": "___ is calling?", "options": ["Who", "Whom", "Whose", "Which"], "answer": "Who", "explanation": "Subject position में 'Who'। (कौन फोन कर रहा है?)"},
    {"question": "From ___ did you get this?", "options": ["whom", "who", "whose", "which"], "answer": "whom", "explanation": "Preposition के बाद 'whom'। (तुम्हें यह किससे मिला?)"}
  ],
  "test-17": [
    {"question": "I have ___ sugar. (थोड़ी, सकारात्मक)", "options": ["a little", "little", "a few", "few"], "answer": "a little", "explanation": "Uncountable + Positive = 'a little'। (मेरे पास थोड़ी चीनी है।)"},
    {"question": "There is ___ hope. (मुश्किल से)", "options": ["little", "a little", "few", "a few"], "answer": "little", "explanation": "Uncountable + Negative = 'little'। (मुश्किल से उम्मीद है।)"},
    {"question": "I have ___ books. (कुछ, सकारात्मक)", "options": ["a few", "few", "a little", "little"], "answer": "a few", "explanation": "Countable + Positive = 'a few'। (मेरे पास कुछ किताबें हैं।)"},
    {"question": "___ people attended. (मुश्किल से)", "options": ["Few", "A few", "Little", "A little"], "answer": "Few", "explanation": "Countable + Negative = 'Few'। (बहुत कम लोग आए।)"},
    {"question": "___ money I had was stolen.", "options": ["The little", "A little", "Little", "The few"], "answer": "The little", "explanation": "Definite + Uncountable = 'The little'। (जो थोड़े पैसे थे वे चोरी हो गए।)"},
    {"question": "___ books I have are old.", "options": ["The few", "A few", "Few", "The little"], "answer": "The few", "explanation": "Definite + Countable = 'The few'। (जो थोड़ी किताबें हैं वे पुरानी हैं।)"},
    {"question": "Is there ___ milk left?", "options": ["any", "some", "no", "none"], "answer": "any", "explanation": "प्रश्न वाक्य में 'any'। (क्या कोई दूध बचा है?)"},
    {"question": "Would you like ___ coffee?", "options": ["some", "any", "no", "none"], "answer": "some", "explanation": "Offer में 'some' आता है। (क्या आप कॉफी लेंगे?)"},
    {"question": "Can I have ___ water?", "options": ["some", "any", "no", "none"], "answer": "some", "explanation": "Request में 'some' आता है। (क्या मुझे पानी मिल सकता है?)"},
    {"question": "I don't have ___ money.", "options": ["any", "some", "no", "none"], "answer": "any", "explanation": "नकारात्मक वाक्य में 'any'। (मेरे पास पैसे नहीं हैं।)"}
  ],
  "test-18": [
    {"question": "He has ___ friends. (एक भी नहीं)", "options": ["no", "any", "some", "none"], "answer": "no", "explanation": "Noun से पहले 'no'। (उसके कोई दोस्त नहीं हैं।)"},
    {"question": "___ of them came. (एक भी नहीं)", "options": ["None", "No", "Any", "Some"], "answer": "None", "explanation": "Of से पहले 'None'। (उनमें से कोई नहीं आया।)"},
    {"question": "___ of you may go first.", "options": ["Either", "Neither", "Both", "Each"], "answer": "Either", "explanation": "दोनों में से कोई एक के लिए 'Either'। (तुम दोनों में से कोई एक पहले जा सकता है।)"},
    {"question": "___ of the roads leads to city.", "options": ["Neither", "Either", "Both", "Each"], "answer": "Neither", "explanation": "दोनों में से कोई भी नहीं के लिए 'Neither'। (कोई रास्ता शहर नहीं जाता।)"},
    {"question": "___ of them are correct.", "options": ["Both", "Either", "Neither", "Each"], "answer": "Both", "explanation": "दोनों के लिए 'Both' + plural verb। (दोनों सही हैं।)"},
    {"question": "___ of the boys was given a book.", "options": ["Each", "Both", "Either", "Neither"], "answer": "Each", "explanation": "हर एक को अलग के लिए 'Each' + singular verb। (हर लड़के को किताब दी गई।)"},
    {"question": "The two brothers love ___.", "options": ["each other", "one another", "themselves", "themself"], "answer": "each other", "explanation": "दो के बीच 'each other'। (दो भाई एक-दूसरे से प्यार करते हैं।)"},
    {"question": "All the team members support ___.", "options": ["one another", "each other", "themselves", "themself"], "answer": "one another", "explanation": "2 से अधिक के बीच 'one another'। (सभी सदस्य एक-दूसरे का समर्थन करते हैं।)"},
    {"question": "The dog bit ___ master.", "options": ["its", "it's", "his", "their"], "answer": "its", "explanation": "जानवर के लिए Possessive 'its'। (कुत्ते ने अपने मालिक को काटा।)"},
    {"question": "___ a beautiful day!", "options": ["It's", "Its", "It", "They're"], "answer": "It's", "explanation": "'It's' = It is। (क्या सुंदर दिन है!)"}
  ],
  "test-19": [
    {"question": "___ going to the market.", "options": ["They're", "Their", "There", "Theirs"], "answer": "They're", "explanation": "'They're' = They are। (वे बाजार जा रहे हैं।)"},
    {"question": "I saw ___ new car.", "options": ["their", "there", "they're", "theirs"], "answer": "their", "explanation": "Possessive 'their'। (मैंने उनकी नई कार देखी।)"},
    {"question": "The keys are ___.", "options": ["there", "their", "they're", "theirs"], "answer": "there", "explanation": "Place के लिए 'there'। (चाबियाँ वहाँ हैं।)"},
    {"question": "This bag is ___.", "options": ["theirs", "their", "there", "they're"], "answer": "theirs", "explanation": "Noun के बिना Possessive 'theirs'। (यह बैग उनका है।)"},
    {"question": "___ a good singer.", "options": ["You're", "Your", "Yours", "You"], "answer": "You're", "explanation": "'You're' = You are। (तुम अच्छे गायक हो।)"},
    {"question": "Is this ___ book?", "options": ["your", "you're", "yours", "you"], "answer": "your", "explanation": "Noun से पहले Possessive Adj 'your'। (क्या यह तुम्हारी किताब है?)"},
    {"question": "This book is ___.", "options": ["yours", "your", "you're", "you"], "answer": "yours", "explanation": "Noun के बिना Possessive Pronoun 'yours'। (यह किताब तुम्हारी है।)"},
    {"question": "___ at the door?", "options": ["Who's", "Whose", "Whom", "Who"], "answer": "Who's", "explanation": "'Who's' = Who is। (दरवाजे पर कौन है?)"},
    {"question": "___ bag is this?", "options": ["Whose", "Who's", "Whom", "Who"], "answer": "Whose", "explanation": "मालिकी के लिए 'Whose'। (यह किसका बैग है?)"},
    {"question": "Myself is Raj. (यह वाक्य...)", "options": ["गलत है", "सही है", "दोनों", "कोई नहीं"], "answer": "गलत है", "explanation": "'I am Raj' या 'My name is Raj' सही है। Myself कर्ता के रूप में नहीं आता।)"}
  ],
  "test-20": [
    {"question": "Me and Ram went to school. (यह वाक्य...)", "options": ["गलत है", "सही है", "दोनों", "कोई नहीं"], "answer": "गलत है", "explanation": "'Ram and I went to school' सही है। Compound Subject में 'I' आता है।)"},
    {"question": "The teacher called Ram and ___.", "options": ["me", "I", "my", "myself"], "answer": "me", "explanation": "Object position में 'me'। (टीचर ने राम और मुझे बुलाया।)"},
    {"question": "Give the book to Sita and ___.", "options": ["me", "I", "my", "myself"], "answer": "me", "explanation": "Preposition के बाद Object 'me'। (सीता और मुझे किताब दो।)"},
    {"question": "She is as smart as ___.", "options": ["I", "me", "my", "mine"], "answer": "I", "explanation": "As...as के बाद Subject form 'I'। (वह उतनी होशियार है जितना मैं।)"},
    {"question": "Nobody knows it better than ___.", "options": ["she", "her", "hers", "herself"], "answer": "she", "explanation": "Than के बाद Subject form 'she'। (इसे उससे बेहतर कोई नहीं जानता।)"},
    {"question": "Let ___ go now.", "options": ["us", "we", "our", "ours"], "answer": "us", "explanation": "'Let' के बाद Object form 'us'। (चलो अब चलते हैं।)"},
    {"question": "All of ___ are students.", "options": ["us", "we", "our", "ours"], "answer": "us", "explanation": "'All of' के बाद Object form 'us'। (हम सब छात्र हैं।)"},
    {"question": "Everyone except ___ was present.", "options": ["her", "she", "hers", "herself"], "answer": "her", "explanation": "'Except' के बाद Object form 'her'। (उसके सिवाय सब हाजिर थे।)"},
    {"question": "The work was done by you and ___.", "options": ["me", "I", "my", "myself"], "answer": "me", "explanation": "'By' के बाद Object form 'me'। (काम तुम्हारे और मेरे द्वारा हुआ।)"},
    {"question": "Between you and ___, this is a secret.", "options": ["me", "I", "my", "mine"], "answer": "me", "explanation": "'Between' के बाद Object form 'me'। (तुम्हारे और मेरे बीच, यह राज है।)"}
  ],
  "test-21": [
    {"question": "___ is your teacher?", "options": ["Who", "Whom", "Whose", "Which"], "answer": "Who", "explanation": "Subject position में 'Who'। (तुम्हारे टीचर कौन हैं?)"},
    {"question": "___ did the teacher scold?", "options": ["Whom", "Who", "Whose", "Which"], "answer": "Whom", "explanation": "Object position में 'Whom'। (टीचर ने किसे डाँटा?)"},
    {"question": "The boy ___ won is my brother.", "options": ["who", "whom", "whose", "which"], "answer": "who", "explanation": "Subject position में 'who'। (जो लड़का जीता वह मेरा भाई है।)"},
    {"question": "The man ___ car was stolen is sad.", "options": ["whose", "who", "whom", "which"], "answer": "whose", "explanation": "मालिकी के लिए 'whose'। (जिस आदमी की कार चोरी हुई वह दुखी है।)"},
    {"question": "This is all ___ I have.", "options": ["that", "which", "who", "whom"], "answer": "that", "explanation": "All के बाद 'that' आता है। (यह सब है जो मेरे पास है।)"},
    {"question": "___ do you want to eat?", "options": ["What", "Which", "Who", "Whom"], "answer": "What", "explanation": "खुला प्रश्न के लिए 'What'। (तुम क्या खाना चाहते हो?)"},
    {"question": "___ shirt do you like? (दो में से)", "options": ["Which", "What", "Who", "Whose"], "answer": "Which", "explanation": "सीमित विकल्पों में से चुनाव के लिए 'Which'। (कौन सी शर्ट पसंद है?)"},
    {"question": "___ money do you have?", "options": ["How much", "How many", "How far", "How long"], "answer": "How much", "explanation": "Uncountable के लिए 'How much'। (तुम्हारे पास कितने पैसे हैं?)"},
    {"question": "___ books are on the table?", "options": ["How many", "How much", "How far", "How long"], "answer": "How many", "explanation": "Countable के लिए 'How many'। (टेबल पर कितनी किताबें हैं?)"},
    {"question": "___ will it take to reach?", "options": ["How long", "How far", "How much", "How many"], "answer": "How long", "explanation": "Duration के लिए 'How long'। (पहुँचने में कितना समय लगेगा?)"}
  ],
  "test-22": [
    {"question": "___ is your house from here?", "options": ["How far", "How long", "How much", "How many"], "answer": "How far", "explanation": "Distance के लिए 'How far'। (तुम्हारा घर यहाँ से कितना दूर है?)"},
    {"question": "___ do you come here?", "options": ["How often", "How long", "How far", "How much"], "answer": "How often", "explanation": "Frequency के लिए 'How often'। (तुम यहाँ कितनी बार आते हो?)"},
    {"question": "I have ___ to tell you.", "options": ["something", "anything", "nothing", "everything"], "answer": "something", "explanation": "सकारात्मक + कुछ के लिए 'something'। (मुझे तुम्हें कुछ बताना है।)"},
    {"question": "There isn't ___ in the box.", "options": ["anything", "something", "nothing", "everything"], "answer": "anything", "explanation": "नकारात्मक वाक्य में 'anything'। (बॉक्स में कुछ नहीं है।)"},
    {"question": "___ was wrong with the plan.", "options": ["Something", "Anything", "Nothing", "Everything"], "answer": "Something", "explanation": "सकारात्मक + कुछ के लिए 'Something'। (योजना में कुछ गलत था।)"},
    {"question": "I heard ___ strange.", "options": ["something", "anything", "nothing", "everything"], "answer": "something", "explanation": "सकारात्मक में 'something'। (मैंने कुछ अजीब सुना।)"},
    {"question": "Do you know ___ about this?", "options": ["anything", "something", "nothing", "everything"], "answer": "anything", "explanation": "प्रश्न में 'anything'। (क्या तुम्हें इसके बारे में कुछ पता है?)"},
    {"question": "___ is possible.", "options": ["Anything", "Something", "Nothing", "Everything"], "answer": "Anything", "explanation": "कोई भी चीज के लिए 'Anything'। (कुछ भी संभव है।)"},
    {"question": "I want to know ___.", "options": ["everything", "something", "anything", "nothing"], "answer": "everything", "explanation": "सब कुछ के लिए 'everything'। (मुझे सब कुछ जानना है।)"},
    {"question": "___ is impossible for him.", "options": ["Nothing", "Something", "Anything", "Everything"], "answer": "Nothing", "explanation": "कुछ भी नहीं (असंभव नहीं) के लिए 'Nothing'। (उसके लिए कुछ भी असंभव नहीं है।)"}
  ],
  "test-23": [
    {"question": "___ was at home.", "options": ["Nobody", "Somebody", "Anybody", "Everybody"], "answer": "Nobody", "explanation": "कोई नहीं = 'Nobody'। (कोई घर पर नहीं था।)"},
    {"question": "___ can solve this problem.", "options": ["Anybody", "Nobody", "Somebody", "Everybody"], "answer": "Anybody", "explanation": "कोई भी = 'Anybody'। (यह समस्या कोई भी हल कर सकता है।)"},
    {"question": "___ is waiting for you.", "options": ["Somebody", "Nobody", "Anybody", "Everybody"], "answer": "Somebody", "explanation": "कोई = 'Somebody'। (कोई तुम्हारा इंतजार कर रहा है।)"},
    {"question": "___ knows the truth.", "options": ["Everybody", "Nobody", "Somebody", "Anybody"], "answer": "Everybody", "explanation": "सभी = 'Everybody'। (सब सच जानते हैं।)"},
    {"question": "Is ___ there?", "options": ["anybody", "somebody", "nobody", "everybody"], "answer": "anybody", "explanation": "प्रश्न में 'anybody'। (क्या वहाँ कोई है?)"},
    {"question": "___ of the students passed.", "options": ["All", "Each", "Every", "Either"], "answer": "All", "explanation": "सभी + plural = 'All'। (सभी छात्र पास हुए।)"},
    {"question": "___ student has a book.", "options": ["Each", "All", "Some", "Any"], "answer": "Each", "explanation": "हर एक + singular = 'Each'। (हर छात्र के पास किताब है।)"},
    {"question": "___ child must obey parents.", "options": ["Every", "Each", "All", "Some"], "answer": "Every", "explanation": "हर एक (समूह) + singular = 'Every'। (हर बच्चे को माता-पिता की बात माननी चाहिए।)"},
    {"question": "___ of us was given a task.", "options": ["Each", "Every", "All", "Both"], "answer": "Each", "explanation": "Each + singular verb। (हम में से हर एक को काम दिया गया।)"},
    {"question": "___ person in the room left.", "options": ["Every", "Each", "All", "Any"], "answer": "Every", "explanation": "Every + singular noun। (कमरे में हर व्यक्ति चला गया।)"}
  ],
  "test-24": [
    {"question": "___ of the two boys is good.", "options": ["Either", "Neither", "Both", "Each"], "answer": "Either", "explanation": "दोनों में से कोई एक (सकारात्मक) = 'Either'। (दो लड़कों में से कोई भी अच्छा है।)"},
    {"question": "___ of my parents is a doctor.", "options": ["Neither", "Either", "Both", "Each"], "answer": "Neither", "explanation": "दोनों में से कोई नहीं = 'Neither'। (मेरे माता-पिता में से कोई डॉक्टर नहीं है।)"},
    {"question": "___ my parents are teachers.", "options": ["Both", "Either", "Neither", "Each"], "answer": "Both", "explanation": "दोनों = 'Both' + plural। (मेरे दोनों माता-पिता टीचर हैं।)"},
    {"question": "He gave a pen to ___ of the students.", "options": ["each", "every", "both", "either"], "answer": "each", "explanation": "हर एक को अलग = 'each'। (उसने हर छात्र को पेन दी।)"},
    {"question": "___ side of the road is a park.", "options": ["Either", "Neither", "Both", "Each"], "answer": "Either", "explanation": "दोनों में से कोई एक तरफ = 'Either'। (सड़क के किसी भी तरफ पार्क है।)"},
    {"question": "You can take ___ bus. (दो में से)", "options": ["either", "neither", "both", "any"], "answer": "either", "explanation": "दोनों में से कोई एक = 'either'। (तुम कोई भी बस ले सकते हो।)"},
    {"question": "___ of the answers is wrong.", "options": ["Neither", "Either", "Both", "Each"], "answer": "Neither", "explanation": "दोनों में से कोई भी गलत नहीं = 'Neither'। (कोई जवाब गलत नहीं है।)"},
    {"question": "The husband and wife love ___.", "options": ["each other", "one another", "themselves", "themself"], "answer": "each other", "explanation": "दो के बीच = 'each other'। (पति-पत्नी एक-दूसरे से प्यार करते हैं।)"},
    {"question": "The classmates help ___.", "options": ["one another", "each other", "themselves", "themself"], "answer": "one another", "explanation": "2 से अधिक के बीच = 'one another'। (सहपाठी एक-दूसरे की मदद करते हैं।)"},
    {"question": "We should respect ___.", "options": ["one another", "each other", "ourselves", "themselves"], "answer": "one another", "explanation": "समूह में परस्पर = 'one another'। (हमें एक-दूसरे का आदर करना चाहिए।)"}
  ],
  "test-25": [
    {"question": "___ is the matter?", "options": ["What", "Which", "Who", "Whose"], "answer": "What", "explanation": "समस्या/बात के लिए 'What'। (क्या बात है?)"},
    {"question": "___ happened here?", "options": ["What", "Which", "Who", "Whose"], "answer": "What", "explanation": "घटना के लिए 'What'। (यहाँ क्या हुआ?)"},
    {"question": "___ made this mistake?", "options": ["Who", "What", "Which", "Whose"], "answer": "Who", "explanation": "व्यक्ति (Subject) के लिए 'Who'। (यह गलती किसने की?)"},
    {"question": "For ___ are you waiting?", "options": ["whom", "who", "whose", "which"], "answer": "whom", "explanation": "Preposition के बाद 'whom'। (तुम किसका इंतजार कर रहे हो?)"},
    {"question": "The girl ___ dress is blue is my sister.", "options": ["whose", "who", "whom", "which"], "answer": "whose", "explanation": "मालिकी = 'whose'। (जिस लड़की की ड्रेस नीली है वह मेरी बहन है।)"},
    {"question": "This is the house ___ Jack built.", "options": ["that", "who", "whom", "whose"], "answer": "that", "explanation": "वस्तु के लिए 'that'। (यह वह घर है जो जैक ने बनाया।)"},
    {"question": "I like the flowers ___ are in the vase.", "options": ["which", "who", "whom", "whose"], "answer": "which", "explanation": "वस्तु के लिए 'which'। (मुझे फूलदान में रखे फूल पसंद हैं।)"},
    {"question": "The reason ___ I called is important.", "options": ["why", "which", "that", "when"], "answer": "why", "explanation": "Reason के बाद 'why'। (जिस कारण मैंने फोन किया वह महत्वपूर्ण है।)"},
    {"question": "The way ___ he talks is rude.", "options": ["that", "which", "who", "whom"], "answer": "that", "explanation": "Way के बाद 'that' (या omit)। (जिस तरह वह बोलता है वह असभ्य है।)"},
    {"question": "She is the very person ___ can help you.", "options": ["that", "who", "whom", "which"], "answer": "that", "explanation": "Very/Same/Only के बाद 'that'। (वह वही व्यक्ति है जो तुम्हारी मदद कर सकता है।)"}
  ],
  "test-26": [
    {"question": "___ am I to do?", "options": ["What", "Which", "Who", "Whose"], "answer": "What", "explanation": "क्रिया के लिए 'What'। (मुझे क्या करना चाहिए?)"},
    {"question": "___ is the time?", "options": ["What", "Which", "Who", "Whose"], "answer": "What", "explanation": "जानकारी के लिए 'What'। (समय क्या हुआ?)"},
    {"question": "___ is better, tea or coffee?", "options": ["Which", "What", "Who", "Whose"], "answer": "Which", "explanation": "सीमित विकल्पों में से चुनाव के लिए 'Which'। (चाय या कॉफी, कौन बेहतर?)"},
    {"question": "About ___ are you talking?", "options": ["whom", "who", "whose", "which"], "answer": "whom", "explanation": "Preposition के बाद 'whom'। (तुम किसके बारे में बात कर रहे हो?)"},
    {"question": "___ do you prefer, this or that?", "options": ["Which", "What", "Who", "Whom"], "answer": "Which", "explanation": "सीमित विकल्पों में से चुनाव के लिए 'Which'। (यह या वह, कौन पसंद है?)"},
    {"question": "I have ___ friends. (बहुत, सकारात्मक)", "options": ["many", "much", "a little", "little"], "answer": "many", "explanation": "Countable + सकारात्मक = 'many'। (मेरे बहुत दोस्त हैं।)"},
    {"question": "There isn't ___ time left.", "options": ["much", "many", "a few", "few"], "answer": "much", "explanation": "Uncountable + नकारात्मक = 'much'। (ज्यादा समय नहीं है।)"},
    {"question": "Did you see ___ birds?", "options": ["any", "some", "no", "none"], "answer": "any", "explanation": "प्रश्न में 'any'। (क्या तुमने कोई पक्षी देखे?)"},
    {"question": "I saw ___ colorful birds.", "options": ["some", "any", "no", "none"], "answer": "some", "explanation": "सकारात्मक में 'some'। (मैंने कुछ रंगीन पक्षी देखे।)"},
    {"question": "There are ___ apples in the basket.", "options": ["some", "any", "no", "none"], "answer": "some", "explanation": "सकारात्मक में 'some'। (टोकरी में कुछ सेब हैं।)"}
  ],
  "test-27": [
    {"question": "___ is hungry.", "options": ["Everyone", "Anyone", "Someone", "No one"], "answer": "Everyone", "explanation": "सभी = 'Everyone' + singular verb। (सबको भूख लगी है।)"},
    {"question": "Is ___ home?", "options": ["anyone", "someone", "no one", "everyone"], "answer": "anyone", "explanation": "प्रश्न में 'anyone'। (क्या कोई घर पर है?)"},
    {"question": "___ left a message for you.", "options": ["Someone", "Anyone", "No one", "Everyone"], "answer": "Someone", "explanation": "कोई (सकारात्मक) = 'Someone'। (किसी ने तुम्हारे लिए संदेश छोड़ा।)"},
    {"question": "___ answered my call.", "options": ["No one", "Someone", "Anyone", "Everyone"], "answer": "No one", "explanation": "किसी ने नहीं = 'No one'। (किसी ने मेरा फोन नहीं उठाया।)"},
    {"question": "He talked to ___.", "options": ["himself", "him", "he", "his"], "answer": "himself", "explanation": "Reflexive = 'himself'। (उसने अपने आप से बात की।)"},
    {"question": "She looked at ___ in the mirror.", "options": ["herself", "her", "she", "hers"], "answer": "herself", "explanation": "Reflexive = 'herself'। (उसने आईने में अपने आप को देखा।)"},
    {"question": "They blamed ___.", "options": ["themselves", "them", "their", "theirs"], "answer": "themselves", "explanation": "Reflexive = 'themselves'। (उन्होंने अपने आप को दोष दिया।)"},
    {"question": "We should believe in ___.", "options": ["ourselves", "us", "we", "our"], "answer": "ourselves", "explanation": "Reflexive = 'ourselves'। (हमें अपने आप पर विश्वास रखना चाहिए।)"},
    {"question": "You must help ___.", "options": ["yourself", "you", "your", "yours"], "answer": "yourself", "explanation": "Reflexive = 'yourself'। (तुम्हें अपनी मदद करनी चाहिए।)"},
    {"question": "The baby fell and hurt ___.", "options": ["itself", "it", "its", "it's"], "answer": "itself", "explanation": "Reflexive = 'itself'। (बच्चा गिरा और चोट लगी।)"}
  ],
  "test-28": [
    {"question": "I bought a new car. ___ is red.", "options": ["It", "Its", "It's", "They"], "answer": "It", "explanation": "Subject = 'It'। (मैंने नई कार खरीदी। वह लाल है।)"},
    {"question": "The bird has lost ___ way.", "options": ["its", "it's", "it", "their"], "answer": "its", "explanation": "Possessive = 'its'। (पक्षी अपना रास्ता भूल गया।)"},
    {"question": "___ raining heavily.", "options": ["It's", "Its", "It", "They're"], "answer": "It's", "explanation": "'It's' = It is। (जोरदार बारिश हो रही है।)"},
    {"question": "I have two sisters. ___ names are Priya and Riya.", "options": ["Their", "They're", "There", "Theirs"], "answer": "Their", "explanation": "Possessive = 'Their'। (मेरी दो बहनें हैं। उनके नाम प्रिया और रिया हैं।)"},
    {"question": "___ are my best friends.", "options": ["They", "Them", "Their", "Theirs"], "answer": "They", "explanation": "Subject = 'They'। (वे मेरे सबसे अच्छे दोस्त हैं।)"},
    {"question": "I gave ___ my book.", "options": ["them", "they", "their", "theirs"], "answer": "them", "explanation": "Object = 'them'। (मैंने उन्हें अपनी किताब दी।)"},
    {"question": "This book is ___.", "options": ["theirs", "their", "them", "they"], "answer": "theirs", "explanation": "Possessive Pronoun = 'theirs'। (यह किताब उनकी है।)"},
    {"question": "___ a good day!", "options": ["Have", "Your", "You're", "Yours"], "answer": "Have", "explanation": "'Have a good day' = अच्छा दिन हो!"},
    {"question": "This is ___ pen. (मेरी)", "options": ["my", "mine", "me", "I"], "answer": "my", "explanation": "Noun से पहले 'my'। (यह मेरी पेन है।)"},
    {"question": "This pen is ___.", "options": ["mine", "my", "me", "I"], "answer": "mine", "explanation": "Noun के बिना 'mine'। (यह पेन मेरी है।)"}
  ],
  "test-29": [
    {"question": "He is ___ friend. (मेरा)", "options": ["my", "mine", "me", "I"], "answer": "my", "explanation": "Noun से पहले Possessive Adj 'my'। (वह मेरा दोस्त है।)"},
    {"question": "This bag is ___. (उसका)", "options": ["his", "him", "he", "her"], "answer": "his", "explanation": "Noun के बिना Possessive Pronoun 'his'। (यह बैग उसका है।)"},
    {"question": "___ won the race. (वह)", "options": ["She", "Her", "Hers", "Herself"], "answer": "She", "explanation": "Subject = 'She'। (वह रेस जीती।)"},
    {"question": "I gave ___ a gift. (उसे)", "options": ["her", "she", "hers", "herself"], "answer": "her", "explanation": "Object = 'her'। (मैंने उसे तोहफा दिया।)"},
    {"question": "This is ___ book. (उसकी)", "options": ["her", "she", "hers", "herself"], "answer": "her", "explanation": "Noun से पहले Possessive Adj 'her'। (यह उसकी किताब है।)"},
    {"question": "This book is ___. (उसकी)", "options": ["hers", "her", "she", "herself"], "answer": "hers", "explanation": "Noun के बिना Possessive Pronoun 'hers'। (यह किताब उसकी है।)"},
    {"question": "___ are playing cricket. (हम)", "options": ["We", "Us", "Our", "Ours"], "answer": "We", "explanation": "Subject = 'We'। (हम क्रिकेट खेल रहे हैं।)"},
    {"question": "He met ___ at the station. (हमें)", "options": ["us", "we", "our", "ours"], "answer": "us", "explanation": "Object = 'us'। (वह स्टेशन पर हमसे मिला।)"},
    {"question": "This is ___ school. (हमारा)", "options": ["our", "we", "us", "ours"], "answer": "our", "explanation": "Noun से पहले 'our'। (यह हमारा स्कूल है।)"},
    {"question": "This school is ___. (हमारा)", "options": ["ours", "our", "we", "us"], "answer": "ours", "explanation": "Noun के बिना 'ours'। (यह स्कूल हमारा है।)"}
  ],
  "test-30": [
    {"question": "___ won the match. (वह)", "options": ["He", "Him", "His", "Himself"], "answer": "He", "explanation": "Subject = 'He'। (वह मैच जीता।)"},
    {"question": "I saw ___ yesterday. (उसे)", "options": ["him", "he", "his", "himself"], "answer": "him", "explanation": "Object = 'him'। (मैंने कल उसे देखा।)"},
    {"question": "This is ___ car. (उसकी)", "options": ["his", "him", "he", "himself"], "answer": "his", "explanation": "Possessive = 'his'। (यह उसकी कार है।)"},
    {"question": "This car is ___. (उसकी)", "options": ["his", "him", "he", "himself"], "answer": "his", "explanation": "'His' = Possessive Adj और Pronoun दोनों में समान। (यह कार उसकी है।)"},
    {"question": "He did it ___. (खुद)", "options": ["himself", "him", "his", "he"], "answer": "himself", "explanation": "Emphasis = 'himself'। (उसने यह खुद किया।)"},
    {"question": "___ finished your homework?", "options": ["Have you", "Your", "You're", "Yours"], "answer": "Have you", "explanation": "'Have you' = क्या तुमने पूरा किया?"},
    {"question": "She is taller than ___.", "options": ["I", "me", "my", "mine"], "answer": "I", "explanation": "Than के बाद Subject form 'I'। (वह मुझसे लंबी है।)"},
    {"question": "The prize was given to Sita and ___.", "options": ["me", "I", "my", "mine"], "answer": "me", "explanation": "Preposition के बाद Object 'me'। (सीता और मुझे इनाम दिया गया।)"},
    {"question": "Let ___ help you.", "options": ["me", "I", "my", "mine"], "answer": "me", "explanation": "'Let' के बाद Object 'me'। (मुझे तुम्हारी मदद करने दो।)"},
    {"question": "It is ___. (मैं)", "options": ["I", "me", "my", "mine"], "answer": "I", "explanation": "Formal English: 'It is I' = यह मैं हूँ।"}
  ]
};
